### ISSUE TITLE
Sometimes assertion fails in synchronization process

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#115]
Probably has something to do with concurrency/synchronisation.

```
Running com.appjangle.server.tests.hooks.TestComplexHookOnServer
nx.persistence.sql.internal.SqlConnectionFactory@d88f893: Created table for nodes test_objecthub
nx.persistence.sql.internal.SqlConnectionFactory@d88f893: Created table for nodes meta
Exception in thread "JreConcurrency-SimpleTimer-for-class com.appjangle.api.hooks.internal.remote.ReloadManager$2" java.lang.AssertionError
	at nx.sync.internal.syncworker.OperationSelector.nextOperation(OperationSelector.java:86)
	at nx.sync.internal.syncworker.SynchronizationProcess.isActive(SynchronizationProcess.java:246)
	at nx.sync.internal.InternalSynchronizedNetwork$2.isSynchronizing(InternalSynchronizedNetwork.java:170)
	at one.engine.nx.internal.CallbackSequencer.testIfCallbackPossible(CallbackSequencer.java:26)
	at one.engine.nx.internal.operations.Common.guardCallback(Common.java:48)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1.onSuccess(LoadAndSynchronizeOperation.java:74)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:235)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:168)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:56)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:32)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
	at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:95)
	at com.ononedb.nextweb.OnedbLink$1.apply(OnedbLink.java:107)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:48)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.OnedbLink.apply(OnedbLink.java:153)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Reload$1.apply(P_Entity_Reload.java:38)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:48)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:48)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.get(PromiseImpl.java:193)
	at io.nextweb.promise.DataPromiseImpl.get(DataPromiseImpl.java:33)
	at com.ononedb.nextweb.OnedbQuery.get(OnedbQuery.java:134)
	at com.appjangle.api.hooks.internal.remote.ReloadManager$2.run(ReloadManager.java:198)
	at delight.concurrency.jre.JreConcurrency$2$1.run(JreConcurrency.java:129)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by mxro** [comment]
Another error:

```
test_create_node_on_local_server(com.appjangle.server.tests.localcache.TestRemoveWithCache)  Time elapsed: 0.054 sec  <<< FAILURE!
java.lang.AssertionError
	at nx.sync.internal.syncworker.OperationSelector.nextOperation(OperationSelector.java:86)
	at nx.sync.internal.syncworker.SynchronizationProcess.isActive(SynchronizationProcess.java:246)
	at nx.sync.internal.InternalSynchronizedNetwork$2.isSynchronizing(InternalSynchronizedNetwork.java:170)
	at one.engine.nx.internal.CallbackSequencer.testIfCallbackPossible(CallbackSequencer.java:26)
	at one.engine.nx.internal.operations.Common.guardCallback(Common.java:48)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1.onSuccess(LoadAndSynchronizeOperation.java:74)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:235)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:168)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:56)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:32)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
	at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:95)
	at com.ononedb.nextweb.OnedbLink$1.apply(OnedbLink.java:107)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.OnedbLink.apply(OnedbLink.java:153)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$2.apply(P_Entity_Select.java:115)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at delight.promise.PromisesCommon$3.apply(PromisesCommon.java:95)
	at delight.promise.PromisesCommon$3.apply(PromisesCommon.java:90)
	at delight.async.AsyncCommon.map(AsyncCommon.java:91)
	at delight.promise.PromisesCommon.resolve(PromisesCommon.java:90)
	at delight.promise.PromisesCommon.resolve(PromisesCommon.java:129)
	at com.appjangle.api.operations.internal.delete.DeleteOperation.perform(DeleteOperation.java:51)
	at com.appjangle.api.operations.OperationsExtension.removeRecursive(OperationsExtension.java:52)
	at com.appjangle.api.operations.OperationsWithEntity$5.apply(OperationsWithEntity.java:78)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at delight.promise.jre.internal.JrePromiseImpl$WrappedOperation.apply(JrePromiseImpl.java:13)
	at delight.async.jre.Async.waitFor(Async.java:37)
	at delight.promise.jre.internal.JrePromiseImpl.get(JrePromiseImpl.java:45)
	at com.ononedb.nextweb.common.DataPromiseImplWithClient.get(DataPromiseImplWithClient.java:43)
	at com.appjangle.server.tests.localcache.TestRemoveWithCache.test_create_node_on_local_server(TestRemoveWithCache.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:43)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by mxro** [comment]
Another error:

```
test_create_node_on_local_server(com.appjangle.server.tests.localcache.TestRemoveWithCache)  Time elapsed: 0.045 sec  <<< FAILURE!
java.lang.AssertionError
	at nx.sync.internal.syncworker.OperationSelector.nextOperation(OperationSelector.java:68)
	at nx.sync.internal.syncworker.SynchronizationProcess.isActive(SynchronizationProcess.java:246)
	at nx.sync.internal.InternalSynchronizedNetwork$2.isSynchronizing(InternalSynchronizedNetwork.java:170)
	at one.engine.nx.internal.CallbackSequencer.testIfCallbackPossible(CallbackSequencer.java:26)
	at one.engine.nx.internal.operations.Common.guardCallback(Common.java:48)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1.onSuccess(LoadAndSynchronizeOperation.java:74)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:235)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:168)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:56)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:32)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
	at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:95)
	at com.ononedb.nextweb.OnedbLink$1.apply(OnedbLink.java:107)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.OnedbLink.apply(OnedbLink.java:153)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$2.apply(P_Entity_Select.java:115)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at delight.promise.PromisesCommon$3.apply(PromisesCommon.java:95)
	at delight.promise.PromisesCommon$3.apply(PromisesCommon.java:90)
	at delight.async.AsyncCommon.map(AsyncCommon.java:91)
	at delight.promise.PromisesCommon.resolve(PromisesCommon.java:90)
	at delight.promise.PromisesCommon.resolve(PromisesCommon.java:129)
	at com.appjangle.api.operations.internal.delete.DeleteOperation.perform(DeleteOperation.java:51)
	at com.appjangle.api.operations.OperationsExtension.removeRecursive(OperationsExtension.java:52)
	at com.appjangle.api.operations.OperationsWithEntity$5.apply(OperationsWithEntity.java:78)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at delight.promise.jre.internal.JrePromiseImpl$WrappedOperation.apply(JrePromiseImpl.java:13)
	at delight.async.jre.Async.waitFor(Async.java:37)
	at delight.promise.jre.internal.JrePromiseImpl.get(JrePromiseImpl.java:45)
	at com.ononedb.nextweb.common.DataPromiseImplWithClient.get(DataPromiseImplWithClient.java:43)
	at com.appjangle.server.tests.localcache.TestRemoveWithCache.test_create_node_on_local_server(TestRemoveWithCache.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:43)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by mxro** [comment]
Another error:

```
Running com.appjangle.api.xtend.tests.sync.TestSyncRemove
Exception in thread "JreConcurrency-SimpleTimer-for-class com.appjangle.api.hooks.internal.remote.ReloadManager$2" java.lang.AssertionError
	at nx.sync.internal.syncworker.OperationSelector.nextOperation(OperationSelector.java:86)
	at nx.sync.internal.syncworker.SynchronizationProcess.isActive(SynchronizationProcess.java:246)
	at nx.sync.internal.InternalSynchronizedNetwork$2.isSynchronizing(InternalSynchronizedNetwork.java:170)
	at one.engine.nx.internal.CallbackSequencer.testIfCallbackPossible(CallbackSequencer.java:26)
	at one.engine.nx.internal.operations.Common.guardCallback(Common.java:48)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1.onSuccess(LoadAndSynchronizeOperation.java:74)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:235)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:168)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:56)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:32)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
	at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:95)
	at com.ononedb.nextweb.OnedbLink$1.apply(OnedbLink.java:107)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.OnedbLink.apply(OnedbLink.java:153)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Reload$1.apply(P_Entity_Reload.java:38)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.get(PromiseImpl.java:193)
	at io.nextweb.promise.DataPromiseImpl.get(DataPromiseImpl.java:33)
	at com.ononedb.nextweb.OnedbQuery.get(OnedbQuery.java:134)
	at com.appjangle.api.hooks.internal.remote.ReloadManager$2.run(ReloadManager.java:198)
	at delight.concurrency.jre.JreConcurrency$2$1.run(JreConcurrency.java:129)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by mxro** [comment]
Another error:

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.085 sec <<< FAILURE!
test_create_node_on_local_server(com.appjangle.server.tests.localcache.TestRemoveWithCache)  Time elapsed: 0.083 sec  <<< FAILURE!
java.lang.AssertionError
	at nx.sync.internal.syncworker.OperationSelector.nextOperation(OperationSelector.java:86)
	at nx.sync.internal.syncworker.SynchronizationProcess.isActive(SynchronizationProcess.java:246)
	at nx.sync.internal.InternalSynchronizedNetwork$2.isSynchronizing(InternalSynchronizedNetwork.java:170)
	at one.engine.nx.internal.CallbackSequencer.testIfCallbackPossible(CallbackSequencer.java:26)
	at one.engine.nx.internal.operations.Common.guardCallback(Common.java:48)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1.onSuccess(LoadAndSynchronizeOperation.java:74)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:235)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:168)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:56)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:32)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
	at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:95)
	at com.ononedb.nextweb.OnedbLink$1.apply(OnedbLink.java:107)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.OnedbLink.apply(OnedbLink.java:153)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$2.apply(P_Entity_Select.java:115)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at delight.promise.PromisesCommon$3.apply(PromisesCommon.java:95)
	at delight.promise.PromisesCommon$3.apply(PromisesCommon.java:90)
	at delight.async.AsyncCommon.map(AsyncCommon.java:91)
	at delight.promise.PromisesCommon.resolve(PromisesCommon.java:90)
	at delight.promise.PromisesCommon.resolve(PromisesCommon.java:129)
	at com.appjangle.api.operations.internal.delete.DeleteOperation.perform(DeleteOperation.java:51)
	at com.appjangle.api.operations.OperationsExtension.removeRecursive(OperationsExtension.java:52)
	at com.appjangle.api.operations.OperationsWithEntity$5.apply(OperationsWithEntity.java:78)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:47)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at delight.promise.jre.internal.JrePromiseImpl$WrappedOperation.apply(JrePromiseImpl.java:13)
	at delight.async.jre.Async.waitFor(Async.java:37)
	at delight.promise.jre.internal.JrePromiseImpl.get(JrePromiseImpl.java:45)
	at com.ononedb.nextweb.common.DataPromiseImplWithClient.get(DataPromiseImplWithClient.java:43)
	at com.appjangle.server.tests.localcache.TestRemoveWithCache.test_create_node_on_local_server(TestRemoveWithCache.java:33)
```
