### ISSUE TITLE
Client does not terminate after RPC call made

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#119]
If running code that makes RPC calls, threads are active after last client closed.

```
"nx.rpcclienturlconnection.internal.engine.UrlConnectionHttpEngine@246b179d" #11 prio=5 os_prio=0 tid=0x00007f91204e7800 nid=0x68b waiting on condition [0x00007f9106916000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000d9ee95b8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by mxro** [comment]
Fixed.
