### ISSUE TITLE
Invalid first index for database reported sometimes

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#12]
Client stops synchronizing

Error message on server

```
Exception in thread "delight.concurrency.schedule.SequentialOperationScheduler" java.lang.RuntimeException: java.lang.Exception: Invalid first index. Database with index was not defined [4594]
    at com.appjangle.database.hooks.internal.VersionDb$6$1$1$1$1.onFailure(VersionDb.java:294)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$2$1.run(SequentialOperationScheduler.java:182)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Invalid first index. Database with index was not defined [4594]
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13$1$1.apply(InternalKeyValueDatabaseImpl.java:403)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13$1$1.apply(InternalKeyValueDatabaseImpl.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$9.apply(InternalKeyValueDatabaseImpl.java:283)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.keyvalue.internal.decorators.SimpleCachedStore$1.apply(SimpleCachedStore.java:82)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.get(SqlStoreImplementation.java:795)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.get(SqlStoreImplementation.java:1)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:71)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.find(InternalKeyValueDatabaseImpl.java:278)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13$1.apply(InternalKeyValueDatabaseImpl.java:397)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:65)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13.apply(InternalKeyValueDatabaseImpl.java:381)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:65)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.first(InternalKeyValueDatabaseImpl.java:370)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.deleteFirst(InternalKeyValueDatabaseImpl.java:203)
    at com.appjangle.persistence.database.internal.statements.DeleteFirstStmt.apply(DeleteFirstStmt.java:14)
    at com.appjangle.persistence.database.internal.statements.DeleteFirstStmt.apply(DeleteFirstStmt.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.execute(InternalKeyValueDatabaseImpl.java:45)
    at com.appjangle.persistence.database.internal.SingleThreadDatabase$1.apply(SingleThreadDatabase.java:36)
    at delight.concurrency.schedule.SequentialOperationScheduler.executeOperation(SequentialOperationScheduler.java:158)
    at delight.concurrency.schedule.SequentialOperationScheduler.runIfRequired(SequentialOperationScheduler.java:138)
    at delight.concurrency.schedule.SequentialOperationScheduler.access$1(SequentialOperationScheduler.java:104)
    at delight.concurrency.schedule.SequentialOperationScheduler$2.onSuccess(SequentialOperationScheduler.java:197)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$4$1$1.apply(InternalKeyValueDatabaseImpl.java:152)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$4$1$1.apply(InternalKeyValueDatabaseImpl.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$2.onSuccess(InternalKeyValueDatabaseImpl.java:92)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$2.onSuccess(InternalKeyValueDatabaseImpl.java:1)
    at delight.async.flow.CallbackAggregator$1.onSuccess(CallbackAggregator.java:73)
    at delight.async.AsyncCommon$3.onSuccess(AsyncCommon.java:120)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$3$1.onSuccess(SqlStoreImplementation.java:829)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$2.run(SqlStoreImplementation.java:777)
```

**Comment by mxro** [comment]
Another exception

```
Exception in thread "delight.concurrency.schedule.SequentialOperationScheduler" java.lang.RuntimeException: java.lang.Exception: Invalid first index. Database with index was not defined [4594]
    at com.appjangle.database.hooks.internal.VersionDb$6$1$1$1$1.onFailure(VersionDb.java:294)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$2$1.run(SequentialOperationScheduler.java:182)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Invalid first index. Database with index was not defined [4594]
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13$1$1.apply(InternalKeyValueDatabaseImpl.java:403)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13$1$1.apply(InternalKeyValueDatabaseImpl.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$9.apply(InternalKeyValueDatabaseImpl.java:283)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.keyvalue.internal.decorators.SimpleCachedStore$1.apply(SimpleCachedStore.java:82)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.get(SqlStoreImplementation.java:795)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.get(SqlStoreImplementation.java:1)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:71)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.find(InternalKeyValueDatabaseImpl.java:278)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13$1.apply(InternalKeyValueDatabaseImpl.java:397)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:65)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13.apply(InternalKeyValueDatabaseImpl.java:381)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:65)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.first(InternalKeyValueDatabaseImpl.java:370)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.deleteFirst(InternalKeyValueDatabaseImpl.java:203)
    at com.appjangle.persistence.database.internal.statements.DeleteFirstStmt.apply(DeleteFirstStmt.java:14)
    at com.appjangle.persistence.database.internal.statements.DeleteFirstStmt.apply(DeleteFirstStmt.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.execute(InternalKeyValueDatabaseImpl.java:45)
    at com.appjangle.persistence.database.internal.SingleThreadDatabase$1.apply(SingleThreadDatabase.java:36)
    at delight.concurrency.schedule.SequentialOperationScheduler.executeOperation(SequentialOperationScheduler.java:158)
    at delight.concurrency.schedule.SequentialOperationScheduler.runIfRequired(SequentialOperationScheduler.java:138)
    at delight.concurrency.schedule.SequentialOperationScheduler.schedule(SequentialOperationScheduler.java:97)
    at com.appjangle.persistence.database.internal.SingleThreadDatabase.execute(SingleThreadDatabase.java:32)
    at com.appjangle.persistence.database.KeyValueDatabase.deleteFirst(KeyValueDatabase.java:100)
    at com.appjangle.database.hooks.internal.VersionDb$5$1.apply(VersionDb.java:253)
    at com.appjangle.database.hooks.internal.VersionDb$5$1.apply(VersionDb.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onSuccess(SequentialOperationScheduler.java:93)
    at delight.concurrency.schedule.SequentialOperationScheduler$2$2.run(SequentialOperationScheduler.java:209)
    ... 4 more
Exception in thread "delight.concurrency.schedule.SequentialOperationScheduler" java.lang.RuntimeException: java.lang.Exception: Invalid first index. Database with index was not defined [4594]
    at com.appjangle.database.hooks.internal.VersionDb$6$1$1$1$1.onFailure(VersionDb.java:294)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$2$1.run(SequentialOperationScheduler.java:182)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Invalid first index. Database with index was not defined [4594]
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13$1$1.apply(InternalKeyValueDatabaseImpl.java:403)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13$1$1.apply(InternalKeyValueDatabaseImpl.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$9.apply(InternalKeyValueDatabaseImpl.java:283)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.keyvalue.internal.decorators.SimpleCachedStore$1.apply(SimpleCachedStore.java:82)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.get(SqlStoreImplementation.java:795)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.get(SqlStoreImplementation.java:1)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:71)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.find(InternalKeyValueDatabaseImpl.java:278)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13$1.apply(InternalKeyValueDatabaseImpl.java:397)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:65)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$13.apply(InternalKeyValueDatabaseImpl.java:381)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:65)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:29)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.first(InternalKeyValueDatabaseImpl.java:370)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.deleteFirst(InternalKeyValueDatabaseImpl.java:203)
    at com.appjangle.persistence.database.internal.statements.DeleteFirstStmt.apply(DeleteFirstStmt.java:14)
    at com.appjangle.persistence.database.internal.statements.DeleteFirstStmt.apply(DeleteFirstStmt.java:1)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.execute(InternalKeyValueDatabaseImpl.java:45)
    at com.appjangle.persistence.database.internal.SingleThreadDatabase$1.apply(SingleThreadDatabase.java:36)
    at delight.concurrency.schedule.SequentialOperationScheduler.executeOperation(SequentialOperationScheduler.java:158)
    at delight.concurrency.schedule.SequentialOperationScheduler.runIfRequired(SequentialOperationScheduler.java:138)
    at delight.concurrency.schedule.SequentialOperationScheduler.access$1(SequentialOperationScheduler.java:104)
    at delight.concurrency.schedule.SequentialOperationScheduler$2.onSuccess(SequentialOperationScheduler.java:197)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$4$1$1.apply(InternalKeyValueDatabaseImpl.java:152)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$4$1$1.apply(InternalKeyValueDatabaseImpl.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$2.onSuccess(InternalKeyValueDatabaseImpl.java:92)
    at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$2.onSuccess(InternalKeyValueDatabaseImpl.java:1)
    at delight.async.flow.CallbackAggregator$1.onSuccess(CallbackAggregator.java:73)
    at delight.async.AsyncCommon$3.onSuccess(AsyncCommon.java:120)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$3$1.onSuccess(SqlStoreImplementation.java:829)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$2.run(SqlStoreImplementation.java:777)
```

**Comment by mxro** [comment]
Reset hookdb data on development system.

**Comment by stellardb** [comment]
Doesn't seem to appear anymore, probably fixed by fixing HookDB data.
