### ISSUE TITLE
Operations.removeRecursive sometimes does not work

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#13]
Steps
- Delete some complex data with Operations.removeRecursive

Findings

An error such as the following occurs:

```
eleted https://objecthub.io/hub/repo/~objects/~thumbnail/versions/~*0 from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/thumbnail
Deleted https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/thumbnail from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta
Deleted https://objecthub.io/hub/repo/~objects/~icon/versions/~*0 from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/icon
Perform commit
Deleted https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/icon/ref from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/icon
Perform commit
Deleted https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/icon from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta
Perform commit
Deleted https://objecthub.io/hub/repo/~objects/~description/versions/~*0 from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/description
Perform commit
Deleted https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/description from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta
Perform commit
Deleted https://objecthub.io/hub/repo/~objects/~title/versions/~*0 from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/title
Perform commit
Deleted https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/title from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta
Perform commit
Deleted https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta/version from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta
Perform commit
Deleted https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main
Perform commit
Deleted https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main from https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n
Perform commit
Exception in thread "Thread-1" Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Cannot remove from node not defined in client [One.reference("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta")].
    at delight.async.jre.Async.waitFor(Async.java:63)
    at delight.promise.jre.internal.JrePromiseImpl.get(JrePromiseImpl.java:24)
    at com.ononedb.nextweb.common.DataPromiseImplWithClient.get(DataPromiseImplWithClient.java:28)
    at com.appjangle.automatic.cloud.objecthub.prod.oneoff.OneOff_DeleteOldBundle.main(OneOff_DeleteOldBundle.java:38)
Caused by: java.lang.IllegalStateException: Cannot remove from node not defined in client [One.reference("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Bundles/.n/Main/.meta")].
    at mx.gwtutils.Preconditions.checkState(Preconditions.java:141)
    at one.engine.nx.internal.operations.RemoveOperation.execute(RemoveOperation.java:28)
    at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
    at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
    at one.core.dsl.grammars.RemoveGrammar$AfterFromNode.in(RemoveGrammar.java:38)
    at com.ononedb.nextweb.plugins.impl.P_Entity_Remove$1$1$2.run(P_Entity_Remove.java:124)
    at one.engine.nx.internal.ClientWrapper$4.process(ClientWrapper.java:185)
    at delight.concurrency.schedule.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:128)
    at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:115)
    at delight.concurrency.schedule.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:79)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mxro** [comment]
Fixed. There was a bug in DeleteOperation.xtend, stop = true not set.
