### ISSUE TITLE
Databases.at(entity).deleteDatabase does not work for nodes with uppercase characters

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#18]
Error reported on server 

```
Exception in thread "delight.concurrency.schedule.SequentialOperationScheduler" java.lang.AssertionError: Found illegal character for Case Sensitive Encoding: ^
   In Key: r:beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*1/data/.n/^New_^Deploy_^Tests_2/.n/4/deploy/main/versions
    at delight.keyvalue.utils.EncodeCaseInsensitiveKey.apply(EncodeCaseInsensitiveKey.java:15)
    at delight.keyvalue.utils.EncodeCaseInsensitiveKey.apply(EncodeCaseInsensitiveKey.java:5)
    at delight.keyvalue.internal.decorators.KeyFilterStore.remove(KeyFilterStore.java:34)
    at delight.keyvalue.internal.decorators.KeyFilterStore.remove(KeyFilterStore.java:34)
    at delight.keyvalue.internal.decorators.KeyFilterStore.remove(KeyFilterStore.java:34)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.remove(PrefixFilterStore.java:40)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.remove(PrefixFilterStore.java:9)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.remove(ExceptionOnStartAndStopStore.java:42)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.remove(ExceptionOnStartAndStopStore.java:8)
    at com.appjangle.database.internal.databases.MainNodeDatabaseRepository$6.apply(MainNodeDatabaseRepository.java:236)
    at com.appjangle.database.internal.databases.MainNodeDatabaseRepository$6.apply(MainNodeDatabaseRepository.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onSuccess(SequentialOperationScheduler.java:93)
    at delight.concurrency.schedule.SequentialOperationScheduler$2$2.run(SequentialOperationScheduler.java:209)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by stellardb** [comment]
Fixed. 

Required to adjust KeyFilterStore to apply filters to outgoing keys, in particlar DecodeCaseInsenstiveKey.
