### ISSUE TITLE
Mysql Exception

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#25]
The following exception is triggered when many nodes are written via commit:

```
Exception in thread "delight.concurrency.schedule.SequentialOperationScheduler" java.lang.RuntimeException: java.lang.RuntimeException: com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
    at delight.concurrency.schedule.SingleInstanceQueueWorker$2.onFailure(SingleInstanceQueueWorker.java:73)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$3.run(SequentialOperationScheduler.java:226)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.processItems(SqlStoreImplementation.java:100)
    at delight.concurrency.schedule.SingleInstanceQueueWorker.perfomActions(SingleInstanceQueueWorker.java:94)
    at delight.concurrency.schedule.SingleInstanceQueueWorker.access$1(SingleInstanceQueueWorker.java:84)
    at delight.concurrency.schedule.SingleInstanceQueueWorker$1.apply(SingleInstanceQueueWorker.java:54)
    at delight.concurrency.schedule.SequentialOperationScheduler.executeOperation(SequentialOperationScheduler.java:158)
    at delight.concurrency.schedule.SequentialOperationScheduler.runIfRequired(SequentialOperationScheduler.java:138)
    at delight.concurrency.schedule.SequentialOperationScheduler.schedule(SequentialOperationScheduler.java:97)
    at delight.concurrency.schedule.SingleInstanceQueueWorker.offer(SingleInstanceQueueWorker.java:48)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.scheduleWrite(SqlStoreImplementation.java:285)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.putSync(SqlStoreImplementation.java:305)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.put(SqlStoreImplementation.java:786)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.put(SqlStoreImplementation.java:1)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.put(SimpleCachedStore.java:37)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:22)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:21)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:1)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:22)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:21)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:1)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:22)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:21)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:1)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at nx.persistence.ext.internal.AsyncMapPersistenceConnection.putNode(AsyncMapPersistenceConnection.java:56)
    at nx.persistence.internal.PersistedNetwork.saveNode(PersistedNetwork.java:120)
    at nx.persistence.internal.PersistedNetwork.doAfterProcessing(PersistedNetwork.java:171)
    at nx.persistence.internal.PersistedNetwork.processStatement(PersistedNetwork.java:187)
    at nx.persistence.internal.cache.GCWatchingNetwork.processStatement(GCWatchingNetwork.java:31)
    at nx.persistence.internal.cache.InternalGCNetwork.processStatement(InternalGCNetwork.java:22)
    at nx.core.grammars.nx.InNetworkGrammar.in(InNetworkGrammar.java:22)
    at nx.versions.internal.VersionManager.assertConnection(VersionManager.java:270)
    at nx.versions.internal.VersionManager.assertVersionList(VersionManager.java:54)
    at nx.versions.internal.VersionManager.getLatestVersionInVersionList(VersionManager.java:210)
    at nx.versions.internal.InternalVersionedNetwork.getLatestVersionForNode(InternalVersionedNetwork.java:126)
    at com.appjangle.database.network.internal.VersionedNetworkConnection.collectResolvedChildren(VersionedNetworkConnection.java:152)
    at com.appjangle.database.network.internal.VersionedNetworkConnection.pullVersions(VersionedNetworkConnection.java:129)
    at nx.remote.messages.v01.PullVersionsMessageData.doOn(PullVersionsMessageData.java:38)
    at com.appjangle.database.network.internal.LocalConnectionReadWrapper.call(LocalConnectionReadWrapper.java:57)
    at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
    at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
    at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
    at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
    at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
    at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
    at nx.remote.utils.FilterRemoteConnectionCallbacks.call(FilterRemoteConnectionCallbacks.java:34)
    at nx.server.auth.internal.AuthorizingConnection.executeAuthorizedRequests(AuthorizingConnection.java:272)
    at nx.server.auth.internal.AuthorizingConnection.access$0(AuthorizingConnection.java:235)
    at nx.server.auth.internal.AuthorizingConnection$1.onSuccess(AuthorizingConnection.java:89)
    at nx.server.auth.internal.AuthorizingConnection$1.onSuccess(AuthorizingConnection.java:1)
    at nx.server.auth.internal.AuthorizingConnection$4$1.apply(AuthorizingConnection.java:149)
    at nx.server.auth.internal.AuthorizingConnection$4$1.apply(AuthorizingConnection.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.async.AsyncCommon.sequentialInt(AsyncCommon.java:256)
    at delight.async.AsyncCommon.access$000(AsyncCommon.java:26)
    at delight.async.AsyncCommon$9.onSuccess(AsyncCommon.java:270)
    at nx.server.auth.internal.AuthorizingConnection$2$1.apply(AuthorizingConnection.java:117)
    at nx.server.auth.internal.AuthorizingConnection$2$1.apply(AuthorizingConnection.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:132)
    at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
    at com.ononedb.nextweb.OnedbClient.destroy(OnedbClient.java:64)
    at com.ononedb.nextweb.OnedbClientInternalImpl$2$1$1.thenDo(OnedbClientInternalImpl.java:180)
    at one.engine.nx.internal.operations.ShutdownOperation$1$1.thenDo(ShutdownOperation.java:53)
    at nx.client.internal.InternalClient$7$1.onSuccess(InternalClient.java:511)
    at delight.concurrency.schedule.BetterAccessThreadImplementation$4.onSuccess(BetterAccessThreadImplementation.java:219)
    at delight.concurrency.schedule.BetterAccessThreadImplementation$3.onSuccess(BetterAccessThreadImplementation.java:175)
    at delight.concurrency.jre.JavaExecutor$2.run(JavaExecutor.java:56)
Caused by: com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2352)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.performInsertOrUpdate(SqlStoreImplementation.java:243)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.writeToSqlDatabase(SqlStoreImplementation.java:140)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.processItems(SqlStoreImplementation.java:98)
    ... 74 more
```

**Comment by objecthub-io** [comment]
Was caused by the server running out of disk space. See [Delete All Binary Logs for MySQL](https://maxrohde.com/2016/08/19/delete-all-binary-logs-for-mysql/).
