### ISSUE TITLE
Server crashes if too big query submitted

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#29]
# Steps
- Upload an object with large binary data (here it was 1.68 mb) to the server
# Findings
- The server becomes unresponsive

```
Exception in thread "delight.concurrency.schedule.SequentialOperationScheduler" java.lang.RuntimeException: java.lang.RuntimeException: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (10563668 > 10485760). You can change this value on the server by setting the max_allowed_packet' variable.
    at delight.concurrency.schedule.SingleInstanceQueueWorker$2.onFailure(SingleInstanceQueueWorker.java:73)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$3.run(SequentialOperationScheduler.java:226)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (10563668 > 10485760). You can change this value on the server by setting the max_allowed_packet' variable.
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.processItems(SqlStoreImplementation.java:100)
    at delight.concurrency.schedule.SingleInstanceQueueWorker.perfomActions(SingleInstanceQueueWorker.java:94)
    at delight.concurrency.schedule.SingleInstanceQueueWorker.access$1(SingleInstanceQueueWorker.java:84)
    at delight.concurrency.schedule.SingleInstanceQueueWorker$1.apply(SingleInstanceQueueWorker.java:54)
    at delight.concurrency.schedule.SequentialOperationScheduler.executeOperation(SequentialOperationScheduler.java:158)
    at delight.concurrency.schedule.SequentialOperationScheduler.runIfRequired(SequentialOperationScheduler.java:138)
    at delight.concurrency.schedule.SequentialOperationScheduler.schedule(SequentialOperationScheduler.java:97)
    at delight.concurrency.schedule.SingleInstanceQueueWorker.offer(SingleInstanceQueueWorker.java:48)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.scheduleWrite(SqlStoreImplementation.java:285)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.putSync(SqlStoreImplementation.java:305)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.put(SqlStoreImplementation.java:786)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.put(SqlStoreImplementation.java:1)
    at delight.keyvalue.internal.decorators.SimpleCachedStore.put(SimpleCachedStore.java:37)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:22)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:21)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:1)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:22)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:21)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:1)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:22)
    at delight.keyvalue.internal.decorators.PrefixFilterStore.put(PrefixFilterStore.java:1)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:21)
    at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.put(ExceptionOnStartAndStopStore.java:1)
    at delight.keyvalue.internal.decorators.KeyFilterStore.put(KeyFilterStore.java:25)
    at nx.persistence.ext.internal.AsyncMapPersistenceConnection.putNode(AsyncMapPersistenceConnection.java:56)
    at nx.persistence.internal.PersistedNetwork.saveNode(PersistedNetwork.java:120)
    at nx.persistence.internal.PersistedNetwork.doAfterProcessing(PersistedNetwork.java:171)
    at nx.persistence.internal.PersistedNetwork.processStatement(PersistedNetwork.java:187)
    at nx.persistence.internal.cache.GCWatchingNetwork.processStatement(GCWatchingNetwork.java:31)
    at nx.persistence.internal.cache.InternalGCNetwork.processStatement(InternalGCNetwork.java:22)
    at nx.versions.internal.VersionManager.storeAsLatestVersion(VersionManager.java:66)
    at nx.versions.internal.InternalVersionedNetwork.processStatement(InternalVersionedNetwork.java:132)
    at nx.versions.internal.InternalVersionedNetwork.processStatement(InternalVersionedNetwork.java:166)
    at com.appjangle.database.network.internal.VersionedNetworkConnection.commit(VersionedNetworkConnection.java:89)
    at nx.remote.messages.v01.CommitMessageData.doOn(CommitMessageData.java:46)
    at com.appjangle.database.network.internal.LocalConnectionWriteWrapper$2.apply(LocalConnectionWriteWrapper.java:156)
    at com.appjangle.database.network.internal.LocalConnectionWriteWrapper$2.apply(LocalConnectionWriteWrapper.java:1)
    at delight.async.AsyncCommon.map(AsyncCommon.java:91)
    at com.appjangle.database.network.internal.LocalConnectionWriteWrapper.applyMessages(LocalConnectionWriteWrapper.java:166)
    at com.appjangle.database.network.internal.LocalConnectionWriteWrapper.access$0(LocalConnectionWriteWrapper.java:148)
    at com.appjangle.database.network.internal.LocalConnectionWriteWrapper$1.onAllValid(LocalConnectionWriteWrapper.java:76)
    at com.appjangle.database.network.internal.PreCommitValidationProcess.start(PreCommitValidationProcess.java:163)
    at com.appjangle.database.network.internal.VersionedNetworkConnection.validate(VersionedNetworkConnection.java:67)
    at com.appjangle.database.network.internal.LocalConnectionWriteWrapper.call(LocalConnectionWriteWrapper.java:71)
    at nx.remote.utils.NxServerUtils.sendMessages2(NxServerUtils.java:142)
    at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:134)
    at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
    at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
    at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
    at nx.remote.utils.FilterRemoteConnectionCallbacks.call(FilterRemoteConnectionCallbacks.java:34)
    at nx.server.auth.internal.AuthorizingConnection.executeAuthorizedRequests(AuthorizingConnection.java:272)
    at nx.server.auth.internal.AuthorizingConnection.access$0(AuthorizingConnection.java:235)
    at nx.server.auth.internal.AuthorizingConnection$1.onSuccess(AuthorizingConnection.java:89)
    at nx.server.auth.internal.AuthorizingConnection$1.onSuccess(AuthorizingConnection.java:1)
    at nx.server.auth.internal.AuthorizingConnection$4$1.apply(AuthorizingConnection.java:149)
    at nx.server.auth.internal.AuthorizingConnection$4$1.apply(AuthorizingConnection.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.async.AsyncCommon.sequentialInt(AsyncCommon.java:256)
    at delight.async.AsyncCommon.access$000(AsyncCommon.java:26)
    at delight.async.AsyncCommon$9.onSuccess(AsyncCommon.java:270)
    at nx.server.auth.internal.AuthorizingConnection$2$1.apply(AuthorizingConnection.java:117)
    at nx.server.auth.internal.AuthorizingConnection$2$1.apply(AuthorizingConnection.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:132)
    at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
    at com.ononedb.nextweb.OnedbClient.destroy(OnedbClient.java:64)
    at com.ononedb.nextweb.OnedbClientInternalImpl$2$1$1.thenDo(OnedbClientInternalImpl.java:180)
    at one.engine.nx.internal.operations.ShutdownOperation$1$1.thenDo(ShutdownOperation.java:53)
    at nx.client.internal.InternalClient$7$1.onSuccess(InternalClient.java:511)
    at delight.concurrency.schedule.BetterAccessThreadImplementation$4.onSuccess(BetterAccessThreadImplementation.java:219)
    at delight.concurrency.schedule.BetterAccessThreadImplementation$3.onSuccess(BetterAccessThreadImplementation.java:175)
    at delight.concurrency.jre.JavaExecutor$2.run(JavaExecutor.java:56)
Caused by: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (10563668 > 10485760). You can change this value on the server by setting the max_allowed_packet' variable.
    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3291)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1983)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.performInsertOrUpdate(SqlStoreImplementation.java:243)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.writeToSqlDatabase(SqlStoreImplementation.java:140)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.processItems(SqlStoreImplementation.java:98)
    ... 78 more
Operation [com.appjangle.persistence.database.internal.SingleThreadDatabase$1@4fd080b4] timed out. (from object: com.appjangle.database.hooks.HookConnection$1@aca2bd2)
java.lang.Exception: Operation [com.appjangle.persistence.database.internal.SingleThreadDatabase$1@4fd080b4] timed out.
  delight.concurrency.schedule.SequentialOperationScheduler$4$1.run(SequentialOperationScheduler.java:253)
  delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)

```

Error when accessing corrupted data:

```
xception in thread "delight.concurrency.schedule.SequentialOperationScheduler" java.lang.RuntimeException: Operation [nx.remote.internal.connections.SingleConcurrentOperationConnection$1@6c49bfe6] failed. Callback cannot be triggered, it was already triggered.
    at delight.concurrency.schedule.SequentialOperationScheduler$2$1.run(SequentialOperationScheduler.java:175)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error while trying to check authorization of messages.
  Error message: Version could not be resolved.
  Version: https://v.objecthub.io/hub/users/main/~demo0912/home/my/~*2/https_/objecthub.io/hub/users/main/~demo0912/home/my/~*2/it/data/img/_data/3
  Resolved Version: Nx.reference(https://v.objecthub.io/hub/users/main/~demo0912/home/my/~*2/https_/objecthub.io/hub/users/main/~demo0912/home/my/~*2/it/data/img/_data/3)
  VersionList: [http://www.linnk.de/s/initialversion, https://v.objecthub.io/hub/users/main/~demo0912/home/my/~*2/https_/objecthub.io/hub/users/main/~demo0912/home/my/~*2/it/data/img/_data/2, https://v.objecthub.io/hub/users/main/~demo0912/home/my/~*2/https_/objecthub.io/hub/users/main/~demo0912/home/my/~*2/it/data/img/_data/3]
    at nx.server.auth.internal.AuthorizingConnection$1.onFailure(AuthorizingConnection.java:96)
    at nx.server.auth.internal.AuthorizingConnection$4$2.apply(AuthorizingConnection.java:163)
    at nx.server.auth.internal.AuthorizingConnection$4$2.apply(AuthorizingConnection.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.async.AsyncCommon.sequentialInt(AsyncCommon.java:256)
    at delight.async.AsyncCommon.access$000(AsyncCommon.java:26)
    at delight.async.AsyncCommon$9.onSuccess(AsyncCommon.java:270)
    at nx.server.auth.internal.AuthorizingConnection$2$1.apply(AuthorizingConnection.java:117)
    at nx.server.auth.internal.AuthorizingConnection$2$1.apply(AuthorizingConnection.java:1)
    at delight.async.AsyncCommon$10.onSuccess(AsyncCommon.java:323)
    at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:132)
    at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
    at com.ononedb.nextweb.OnedbClient.destroy(OnedbClient.java:64)
    at com.ononedb.nextweb.OnedbClientInternalImpl$2$1$1.thenDo(OnedbClientInternalImpl.java:180)
    at one.engine.nx.internal.operations.ShutdownOperation$1$1.thenDo(ShutdownOperation.java:53)
    at nx.client.internal.InternalClient$7$1.onSuccess(InternalClient.java:511)
    at delight.concurrency.schedule.BetterAccessThreadImplementation$4.onSuccess(BetterAccessThreadImplementation.java:219)
    at delight.concurrency.schedule.BetterAccessThreadImplementation$3.onSuccess(BetterAccessThreadImplementation.java:175)
    at delight.concurrency.jre.JavaExecutor$2.run(JavaExecutor.java:56)
Caused by: java.lang.AssertionError: Version could not be resolved.
  Version: https://v.objecthub.io/hub/users/main/~demo0912/home/my/~*2/https_/objecthub.io/hub/users/main/~demo0912/home/my/~*2/it/data/img/_data/3
  Resolved Version: Nx.reference(https://v.objecthub.io/hub/users/main/~demo0912/home/my/~*2/https_/objecthub.io/hub/users/main/~demo0912/home/my/~*2/it/data/img/_data/3)
  VersionList: [http://www.linnk.de/s/initialversion, https://v.objecthub.io/hub/users/main/~demo0912/home/my/~*2/https_/objecthub.io/hub/users/main/~demo0912/home/my/~*2/it/data/img/_data/2, https://v.objecthub.io/hub/users/main/~demo0912/home/my/~*2/https_/objecthub.io/hub/users/main/~demo0912/home/my/~*2/it/data/img/_data/3]
    at nx.versions.internal.VersionManager.getLatestVersionInVersionList(VersionManager.java:248)
    at nx.versions.internal.VersionManager.getLatestVersionInVersionList(VersionManager.java:218)
    at nx.versions.internal.InternalVersionedNetwork.getLatestVersionForNode(InternalVersionedNetwork.java:126)
    at nx.sync.internal.InternalSyncUtils.translateTreeIntoVersionedTreeHelperInternal(InternalSyncUtils.java:84)
    at nx.sync.internal.InternalSyncUtils.translateTreeIntoVersionedTreeHelperInternal(InternalSyncUtils.java:123)
    at nx.sync.internal.InternalSyncUtils.translateTreeIntoVersionedTreeHelperInternal(InternalSyncUtils.java:123)
    at nx.sync.internal.InternalSyncUtils.translateTreeIntoVersionedTreeHelper(InternalSyncUtils.java:142)
    at nx.sync.internal.InternalSyncUtils.translateTreeIntoVersionedTree(InternalSyncUtils.java:161)
    at com.appjangle.database.network.internal.VersionedNetworkConnection.resolve(VersionedNetworkConnection.java:210)
    at nx.remote.messages.v01.ResolveMessageData.doOn(ResolveMessageData.java:32)
    at com.appjangle.database.network.internal.LocalConnectionReadWrapper.call(LocalConnectionReadWrapper.java:57)
    at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
    at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
    at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
    at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
    at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
    at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
    at nx.remote.internal.connections.BlockShutdownOperationConnection.call(BlockShutdownOperationConnection.java:21)
    at nx.remote.connections.ClientThreadSynchronizedConnection.call(ClientThreadSynchronizedConnection.java:39)
    at nx.remote.internal.connections.IncomingCallbackLinearizer.call(IncomingCallbackLinearizer.java:43)
    at nx.remote.internal.connections.InternalAuthorizingRemoteConnection.call(InternalAuthorizingRemoteConnection.java:84)
    at nx.remote.internal.wrapper.InternalRemoteConnectionWrapper.executeSendCache(InternalRemoteConnectionWrapper.java:425)
    at nx.remote.internal.wrapper.InternalRemoteConnectionWrapper.sendCacheItems(InternalRemoteConnectionWrapper.java:395)
    at nx.remote.internal.wrapper.InternalRemoteConnectionWrapper.readFromServerUnprotected(InternalRemoteConnectionWrapper.java:304)
    at nx.remote.internal.wrapper.InternalRemoteConnectionWrapper.readFromServer(InternalRemoteConnectionWrapper.java:265)
    at nx.remote.internal.InternalRemoteConnectionFacade.readFromServer(InternalRemoteConnectionFacade.java:119)
    at nx.sync.internal.syncworker.cache.MessageSender.sendReadMessagesToServer(MessageSender.java:382)
    at nx.sync.internal.syncworker.pull.PullExecutor.doSentToServer(PullExecutor.java:85)
    at nx.sync.internal.syncworker.SynchronizationProcess.tick(SynchronizationProcess.java:215)
    at nx.sync.internal.syncworker.SynchronizationProcess.tick(SynchronizationProcess.java:211)
    at nx.sync.internal.syncworker.SynchronizationProcess.receiveFromClient(SynchronizationProcess.java:260)
    at nx.sync.internal.syncworker.Synchronizer.synchronizeProtected(Synchronizer.java:49)
    at nx.sync.internal.syncworker.Synchronizer.synchronize(Synchronizer.java:43)
    at nx.sync.internal.InternalSynchronizedNetwork.synchronize(InternalSynchronizedNetwork.java:140)
    at nx.client.internal.InternalClient.synchronize(InternalClient.java:208)
    at nx.sync.grammars.SynchronizeWithCallbackGrammar$AndThen.andThen(SynchronizeWithCallbackGrammar.java:39)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:174)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:53)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:1)
    at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
    at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
    at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
    at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:90)
    at com.ononedb.nextweb.OnedbLink$1.apply(OnedbLink.java:99)
    at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:48)
    at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:83)
    at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:29)
    at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:44)
    at com.ononedb.nextweb.OnedbLink.apply(OnedbLink.java:511)
    at delight.concurrency.Concurrent.sequentialInt(Concurrent.java:111)
    at delight.concurrency.Concurrent.access$1(Concurrent.java:84)
    at delight.concurrency.Concurrent$3.onSuccess(Concurrent.java:132)
    at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:132)
    at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
    at com.ononedb.nextweb.OnedbLink$1$1.thenDo(OnedbLink.java:103)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1$1.run(LoadAndSynchronizeOperation.java:86)
    at one.engine.nx.internal.CallbackSequencer$1.run(CallbackSequencer.java:43)
    at one.engine.nx.internal.ClientWrapper$4.process(ClientWrapper.java:185)
    at delight.concurrency.schedule.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:128)
    at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:115)
    at delight.concurrency.schedule.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:79)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by mxro** [comment]
Fixed.
