### ISSUE TITLE
Sometimes VersionDB Storage fails

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#30]
Error reported

```
Exception in thread "delight.concurrency.schedule.SequentialOperationScheduler" java.lang.RuntimeException: java.lang.Exception: Operation [com.appjangle.persistence.database.internal.SingleThreadDatabase$1@40307a63] timed out.
    at com.appjangle.database.hooks.internal.VersionDb$6$1$1$1$1.onFailure(VersionDb.java:294)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$4$1.run(SequentialOperationScheduler.java:253)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Operation [com.appjangle.persistence.database.internal.SingleThreadDatabase$1@40307a63] timed out.
    ... 5 more
Exception in thread "delight.concurrency.schedule.SequentialOperationScheduler" java.lang.RuntimeException: Operation [com.appjangle.persistence.database.internal.SingleThreadDatabase$1@40307a63] successful. Callback cannot be triggered, it was already triggered.
    at delight.concurrency.schedule.SequentialOperationScheduler$2$2.run(SequentialOperationScheduler.java:204)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by stellardb** [comment]
Is not happening anymore.
