### ISSUE TITLE
Error when running service when there is no user logged in

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#33]
# Steps
- Go to a Micro Service Object without having signed in as a user
- Run the micro service
# Findings

The service won't run. 

The following exception is reported on the server.

```
Exception in thread "delight.concurrency.schedule.BetterAccessThreadImplementation" java.lang.NullPointerException
    at com.appjangle.rest.nodes.lambda.LambdaScriptExecutionService$1.apply(LambdaScriptExecutionService.java:127)
    at com.appjangle.rest.nodes.lambda.LambdaScriptExecutionService$1.apply(LambdaScriptExecutionService.java:1)
    at delight.promise.internal.PromiseImpl$3.onSuccess(PromiseImpl.java:207)
    at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:132)
    at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
    at com.appjangle.api.queries.Queries$6$1.apply(Queries.java:345)
    at com.appjangle.api.queries.Queries$6$1.apply(Queries.java:1)
    at io.nextweb.promise.utils.CallbackUtils$2.onSuccess(CallbackUtils.java:66)
    at io.nextweb.promise.DataPromiseImpl$1.onSuccess(DataPromiseImpl.java:72)
    at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:132)
    at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
    at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1$1$2.thenDo(P_Entity_Select.java:310)
    at one.engine.nx.internal.operations.SelectNodesOperation$1.thenDo(SelectNodesOperation.java:77)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1.onSuccess(LoadAndSynchronizeOperation.java:67)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$3.onSuccess(LoadAndSynchronizeOperation.java:262)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$3.onSuccess(LoadAndSynchronizeOperation.java:1)
    at delight.async.flow.CallbackMap$1.onSuccess(CallbackMap.java:50)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$4.onSuccess(LoadAndSynchronizeOperation.java:282)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:237)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:165)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:276)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:165)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:53)
    at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:1)
    at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
    at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
    at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
    at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:90)
    at one.engine.nx.internal.operations.SelectNodesOperation.execute(SelectNodesOperation.java:34)
    at one.engine.nx.internal.operations.SelectNodesOperation.execute(SelectNodesOperation.java:1)
    at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
    at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
    at one.core.dsl.grammars.select.SelectChildrenWithQueryGrammar.and(SelectChildrenWithQueryGrammar.java:28)
    at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1$1.run(P_Entity_Select.java:296)
    at one.engine.nx.internal.ClientWrapper$4.process(ClientWrapper.java:185)
    at delight.concurrency.schedule.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:128)
    at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:115)
    at delight.concurrency.schedule.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:79)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by objecthub-io** [comment]
No, exception occurs only when no user can be identified for the service.

E.g. the node is on a path that does not belong to a user.

As for instance of objects on the ObjectHub public repo.

**Comment by objecthub-io** [comment]
Fixed.
