### ISSUE TITLE
Sometimes wrong version stored in localStorage

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#4]
Sometimes, in particular with ObjectHub object's title, a synchronization error occurs that a wrong version from the server is received.

The correct version would be:

localStorage.getItem("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_/.meta/title")
"O[5,1,4,3,4,2,1,["optser.v01.OptVersion/2993221691","Variable Item (MA)","https://v.beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my…ectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_/.meta/_title/4","https://v.beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my…ectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_/.meta/_title/3","https://beta.objecthub.io/dev/~100/~hub/hub/repo/~objects/~title/versions/~*0"],0,7]"

Which includes Version 4 as the last version.

But erroneously the client sometimes has the state with Version 4 and the attribute (title) already connected.

**Comment by mxro** [comment]
Another instance when error occurred:

```
java.lang.Exception: Received invalid new version from server with number [4].
  Error while applying to local network [Connection between nodes [Nx.reference(https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~…tHub_Web/.n/Components/.n/Code/.n/HTML/.n/CodeMirror-HTML__MA_/.meta/title) -> One.reference("https://beta.objecthub.io/dev/~100/~hub/hub/repo/~objects/~title/versions/~*0")] is already defined in network. Cannot append node.]
  Versions to be applied: [[4]]<br />
Unknown.$collect(JsArrayString.java:42)<br/>
Unknown.fillInStackTrace_1(StackTraceCreator.java:174)<br/>
Unknown.fillInStackTrace(StackTraceCreator.java:508)<br/>
Unknown.$fillInStackTrace(Throwable.java:72)<br/>
Unknown.$$init_1133(Throwable.java:46)<br/>
Unknown.Throwable_1(Throwable.java:52)<br/>
Unknown.Exception_1(Exception.java:29)<br/>
Unknown.$callFailureCallback(NewVersionsResponse.java:142)<br/>
Unknown.apply_692(NewVersionsResponse.java:50)<br/>
Unknown.$doProcessResponsesFromServer(PullExecutor.java:122)<br/>
Unknown.$tick_1(SynchronizationProcess.java:221)<br/>
Unknown.$receiveFromServerOrCache(PullProcess.java:34)<br/>
Unknown.onNewVersions_2(PullVersionsHandler.java:38)<br/>
Unknown.onNewVersions_1(MessageSender.java:219)<br/>
Unknown.onNewVersions(NodeFilterIncomingConnection.java:83)<br/>
Unknown.onNewVersions(NodeFilterIncomingConnection.java:83)<br/>
Unknown.pushOn_7(PullVersionsResponseData.java:62)<br/>
Unknown.process_3(RemoteToLocalCallbackConverter.java:63)<br/>
Unknown.$processStepsGuarded(ThreadSpace.java:33)<br/>
Unknown.processSteps(ThreadSpace.java:54)<br/>
Unknown.$onSuccess_73(RemoteToLocalCallbackConverter.java:90)<br/>
Unknown.onSuccess_149(RemoteToLocalCallbackConverter.java:30)<br/>
Unknown.$onSuccess_70(InternalAuthorizingRemoteConnection.java:91)<br/>
Unknown.onSuccess_146(InternalAuthorizingRemoteConnection.java:87)<br/>
Unknown.process_1(CallbackSorter.java:73)<br/>
Unknown.$processItems(BetterAccessThreadImplementation.java:128)<br/>
Unknown.$run_0(BetterAccessThreadImplementation.java:115)<br/>
Unknown.run_53(BetterAccessThreadImplementation.java:79)<br/>
Unknown.execute_10(GwtConcurrencyImpl.java:133)<br/>
Unknown.$runProtected(BetterAccessThreadImplementation.java:74)<br/>
Unknown.$startIfRequired(BetterAccessThreadImplementation.java:59)<br/>

```

**Comment by mxro** [comment]
Example of incorrect version

```
"O[5,1,4,3,3,2,1,["optser.v01.OptVersion/2993221691","Main (MA)","https://v.beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my…ub_Web/.n/Screens/.n/Index___Main_Page/.n/Main/.n/Main__MA_/.meta/_title/3","https://v.beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my…ub_Web/.n/Screens/.n/Index___Main_Page/.n/Main/.n/Main__MA_/.meta/_title/2","https://beta.objecthub.io/dev/~100/~hub/hub/repo/~objects/~title/versions/~*0"],0,7]"
```

And the related correct version

```
"O[5,1,4,3,4,2,1,["optser.v01.OptVersion/2993221691","Main (MA)","https://v.beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my…ub_Web/.n/Screens/.n/Index___Main_Page/.n/Main/.n/Main__MA_/.meta/_title/4","https://v.beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my…ub_Web/.n/Screens/.n/Index___Main_Page/.n/Main/.n/Main__MA_/.meta/_title/3","https://beta.objecthub.io/dev/~100/~hub/hub/repo/~objects/~title/versions/~*0"],0,7]"
```

**Comment by mxro** [comment]
Also occurred in unit test TestComplexHookOnServer

```
Exception in thread "Thread-79258" java.lang.RuntimeException: Uncaught background exception: Received invalid new version from server with number [3].
  Error while applying to local network [Connection between nodes [Nx.reference(http://localhost:80/hooktest/.n/folder4) -> One.reference("http://localhost:80/hooktest/types/folder")] is already defined in network. Cannot append node.]
  Versions to be applied: [[2, 3, 4]] from class: class com.ononedb.nextweb.jre.OnedbJreFactory$2
    at com.ononedb.nextweb.jre.OnedbNextwebEngineJre$2$1.run(OnedbNextwebEngineJre.java:164)
Caused by: java.lang.Exception: Received invalid new version from server with number [3].
  Error while applying to local network [Connection between nodes [Nx.reference(http://localhost:80/hooktest/.n/folder4) -> One.reference("http://localhost:80/hooktest/types/folder")] is already defined in network. Cannot append node.]
  Versions to be applied: [[2, 3, 4]]
    at nx.sync.internal.syncworker.pull.operations.NewVersionsResponse.callFailureCallback(NewVersionsResponse.java:139)
    at nx.sync.internal.syncworker.pull.operations.NewVersionsResponse.apply(NewVersionsResponse.java:50)
    at nx.sync.internal.syncworker.pull.PullExecutor.doProcessResponsesFromServer(PullExecutor.java:122)
    at nx.sync.internal.syncworker.SynchronizationProcess.tick(SynchronizationProcess.java:221)
    at nx.sync.internal.syncworker.pull.PullProcess.receiveFromServerOrCache(PullProcess.java:34)
    at nx.sync.internal.syncworker.pull.PullVersionsHandler$PullVersionsCallbackHandler.onUnchanged(PullVersionsHandler.java:62)
    at nx.sync.internal.syncworker.cache.MessageSender$CacheReceiveCallback.onUnchanged(MessageSender.java:241)
    at nx.filter.internal.NodeFilterIncomingConnection$1.onUnchanged(NodeFilterIncomingConnection.java:88)
    at nx.filter.internal.NodeFilterIncomingConnection$1.onUnchanged(NodeFilterIncomingConnection.java:88)
    at nx.remote.messages.v03.PullVersionsResponseData.pushOn(PullVersionsResponseData.java:64)
    at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter$1.process(RemoteToLocalCallbackConverter.java:63)
    at delight.concurrency.schedule.ThreadSpace.processStepsGuarded(ThreadSpace.java:33)
    at delight.concurrency.schedule.ThreadSpace.processSteps(ThreadSpace.java:54)
    at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onSuccess(RemoteToLocalCallbackConverter.java:90)
    at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onSuccess(RemoteToLocalCallbackConverter.java:1)
    at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onSuccess(InternalAuthorizingRemoteConnection.java:91)
    at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onSuccess(InternalAuthorizingRemoteConnection.java:1)
    at mx.gwtutils.async.CallbackSorter$1.process(CallbackSorter.java:73)
    at delight.concurrency.schedule.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:128)
    at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:115)
    at delight.concurrency.schedule.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:79)
    at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mxro** [comment]
Changed
- Improved the reload manager to always reload children before their parents
- Improved HookPromise so that in child added event, the added child is only reloaded and not resolved.

**Comment by mxro** [comment]
Another error 

```
Unhandled exception caught by engine: Received invalid new version from server with number [4].
  Error while applying to local network [Connection between nodes [Nx.reference(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Documentation/.n/API/.n/ObjectHub/.n/ObjectHub/.meta/title) -> One.reference("https://objecthub.io/hub/repo/~objects/~title/versions/~*0")] is already defined in network. Cannot append node.]
  Versions to be applied: [[2, 3, 4]] from com.ononedb.nextweb.js.internal.OnedbJsFactory$2@d2fc
0.js:114951 java.lang.Exception: Received invalid new version from server with number [4].
  Error while applying to local network [Connection between nodes [Nx.reference(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Pages/.n/Documentation/.n/API/.n/ObjectHub/.n/ObjectHub/.meta/title) -> One.reference("https://objecthub.io/hub/repo/~objects/~title/versions/~*0")] is already defined in network. Cannot append node.]
  Versions to be applied: [[2, 3, 4]]<br />
Unknown.$collect(JsArrayString.java:42)<br/>
Unknown.fillInStackTrace_1(StackTraceCreator.java:174)<br/>
Unknown.fillInStackTrace(StackTraceCreator.java:508)<br/>
Unknown.$fillInStackTrace(Throwable.java:72)<br/>
Unknown.$$init_1142(Throwable.java:46)<br/>
Unknown.Throwable_1(Throwable.java:52)<br/>
Unknown.Exception_1(Exception.java:29)<br/>
Unknown.$callFailureCallback(NewVersionsResponse.java:142)<br/>
Unknown.apply_694(NewVersionsResponse.java:50)<br/>
Unknown.$doProcessResponsesFromServer(PullExecutor.java:122)<br/>
Unknown.$tick_1(SynchronizationProcess.java:221)<br/>
Unknown.$receiveFromServerOrCache(PullProcess.java:34)<br/>
Unknown.onNewVersions_2(PullVersionsHandler.java:38)<br/>
Unknown.onNewVersions_1(MessageSender.java:219)<br/>
Unknown.onNewVersions(NodeFilterIncomingConnection.java:83)<br/>
Unknown.onNewVersions(NodeFilterIncomingConnection.java:83)<br/>
Unknown.pushOn_7(PullVersionsResponseData.java:62)<br/>
Unknown.process_3(RemoteToLocalCallbackConverter.java:63)<br/>
Unknown.$processStepsGuarded(ThreadSpace.java:33)<br/>
Unknown.processSteps(ThreadSpace.java:54)<br/>
Unknown.$onSuccess_74(RemoteToLocalCallbackConverter.java:90)<br/>
Unknown.onSuccess_149(RemoteToLocalCallbackConverter.java:30)<br/>
Unknown.$onSuccess_71(InternalAuthorizingRemoteConnection.java:91)<br/>
Unknown.onSuccess_146(InternalAuthorizingRemoteConnection.java:87)<br/>
Unknown.process_1(CallbackSorter.java:73)<br/>
Unknown.$processItems(BetterAccessThreadImplementation.java:128)<br/>
Unknown.$run_0(BetterAccessThreadImplementation.java:115)<br/>
Unknown.run_54(BetterAccessThreadImplementation.java:79)<br/>
Unknown.execute_10(GwtConcurrencyImpl.java:133)<br/>
Unknown.$runProtected(BetterAccessThreadImplementation.java:74)<br/>
Unknown.$startIfRequired(BetterAccessThreadImplementation.java:59)<br/>
Unknown.processSteps_0(BetterAccessThreadImplementation.java:390)<br/>
Unknown.$attemptToExecuteCallback(CallbackSorter.java:86)<br/>
Unknown.$onSuccess_62(CallbackSorter.java:125)<br/>
Unknown.onSuccess_131(CallbackSorter.java:112)<br/>
Unknown.$executeCallback(ClientThreadSynchronizedConnection.java:74)<br/>
Unknown.$onSuccess_67(ClientThreadSynchronizedConnection.java:92)<br/>
Unknown.onSuccess_140(ClientThreadSynchronizedConnection.java:91)<br/>
Unknown.$onSuccess_68(CachePullUpdatesClientConnection.java:92)<br/>
Unknown.onSuccess_141(CachePullUpdatesClientConnection.java:63)<br/>
Unknown.$process_4(GwtRpcResponseReader.java:24)<br/>
Unknown.onResponseReceived_0(GwtHttpRemoteConnection.java:50)<br/>
Unknown.$fireOnResponseReceived(Request.java:258)<br/>
Unknown.onReadyStateChange(RequestBuilder.java:412)<br/>
Unknown.anonymous(XMLHttpRequest.java:351)<br/>
Unknown.apply_481(Impl.java:189)<br/>
Unknown.entry0(Impl.java:249)<br/>
Unknown.anonymous(Impl.java:70)<br/>
-end of stack trace
```

**Comment by mxro** [comment]
Might occur now mostly when localStorage was cleared because of overflow.

**Comment by mxro** [comment]
Occured while synchronizing a folder e.g. having the same folder open in two windows. Then adding a folder in window 1; in window 2 the following error occurs:

```
baseJs.js:70 Exception reported: Received invalid new version from server with number [3].
  Error while applying to local network [Connection between nodes [Nx.reference(https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*1/data/.n/New_Test/.n/One) -> One.value(meta).at("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*1/data/.n/New_Test/.n/One/.meta")] is already defined in network. Cannot append node.]
  Versions to be applied: [[2, 3, 4, 5]]
baseJs.js:71 java.lang.Exception: Received invalid new version from server with number [3].
  Error while applying to local network [Connection between nodes [Nx.reference(https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*1/data/.n/New_Test/.n/One) -> One.value(meta).at("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*1/data/.n/New_Test/.n/One/.meta")] is already defined in network. Cannot append node.]
  Versions to be applied: [[2, 3, 4, 5]]<br />
Unknown.$collect(JsArrayString.java:42)<br/>
Unknown.fillInStackTrace_1(StackTraceCreator.java:174)<br/>
Unknown.fillInStackTrace(StackTraceCreator.java:508)<br/>
Unknown.$fillInStackTrace(Throwable.java:72)<br/>
Unknown.$$init_1142(Throwable.java:46)<br/>
Unknown.Throwable_1(Throwable.java:52)<br/>
Unknown.Exception_1(Exception.java:29)<br/>
Unknown.$callFailureCallback(NewVersionsResponse.java:142)<br/>
Unknown.apply_694(NewVersionsResponse.java:50)<br/>
Unknown.$doProcessResponsesFromServer(PullExecutor.java:122)<br/>
Unknown.$tick_1(SynchronizationProcess.java:221)<br/>
Unknown.$receiveFromServerOrCache(PullProcess.java:34)<br/>
Unknown.onNewVersions_2(PullVersionsHandler.java:38)<br/>
Unknown.onNewVersions_1(MessageSender.java:219)<br/>
Unknown.onNewVersions(NodeFilterIncomingConnection.java:83)<br/>
Unknown.onNewVersions(NodeFilterIncomingConnection.java:83)<br/>
Unknown.pushOn_7(PullVersionsResponseData.java:62)<br/>
Unknown.process_3(RemoteToLocalCallbackConverter.java:63)<br/>
Unknown.$processStepsGuarded(ThreadSpace.java:33)<br/>
Unknown.processSteps(ThreadSpace.java:54)<br/>
Unknown.$onSuccess_74(RemoteToLocalCallbackConverter.java:90)<br/>
Unknown.onSuccess_149(RemoteToLocalCallbackConverter.java:30)<br/>
Unknown.$onSuccess_71(InternalAuthorizingRemoteConnection.java:91)<br/>
Unknown.onSuccess_146(InternalAuthorizingRemoteConnection.java:87)<br/>
Unknown.process_1(CallbackSorter.java:73)<br/>
Unknown.$processItems(BetterAccessThreadImplementation.java:128)<br/>
Unknown.$run_0(BetterAccessThreadImplementation.java:115)<br/>
Unknown.run_54(BetterAccessThreadImplementation.java:79)<br/>
Unknown.execute_10(GwtConcurrencyImpl.java:133)<br/>
Unknown.$runProtected(BetterAccessThreadImplementation.java:74)<br/>
Unknown.$startIfRequired(BetterAccessThreadImplementation.java:59)<br/>
Unknown.processSteps_0(BetterAccessThreadImplementation.java:390)<br/>
Unknown.$attemptToExecuteCallback(CallbackSorter.java:86)<br/>
Unknown.$onSuccess_62(CallbackSorter.java:125)<br/>
Unknown.onSuccess_131(CallbackSorter.java:112)<br/>
Unknown.$executeCallback(ClientThreadSynchronizedConnection.java:74)<br/>
Unknown.$onSuccess_67(ClientThreadSynchronizedConnection.java:92)<br/>
Unknown.onSuccess_140(ClientThreadSynchronizedConnection.java:91)<br/>
Unknown.$onSuccess_68(CachePullUpdatesClientConnection.java:92)<br/>
Unknown.onSuccess_141(CachePullUpdatesClientConnection.java:63)<br/>
Unknown.$process_4(GwtRpcResponseReader.java:24)<br/>
Unknown.onResponseReceived_0(GwtHttpRemoteConnection.java:50)<br/>
Unknown.$fireOnResponseReceived(Request.java:258)<br/>
Unknown.onReadyStateChange(RequestBuilder.java:412)<br/>
Unknown.anonymous(XMLHttpRequest.java:351)<br/>
Unknown.apply_481(Impl.java:189)<br/>
Unknown.entry0(Impl.java:249)<br/>
Unknown.anonymous(Impl.java:70)<br/>
-end of stack trace
```

**Comment by mxro** [comment]
Another instance:

```
java.lang.Exception: Received invalid new version from server with number [2].
  Error while applying to local network [Connection between nodes [Nx.reference(https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~…ub_Web/.n/Components/.n/Deployment/.n/Deploy_Panel/app_js/imports/v1465852) -> One.value(Random_String).at("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~…b/.n/Components/.n/Deployment/.n/Deploy_Panel/app_js/imports/v1465852/name")] is already defined in network. Cannot append node.]
  Versions to be applied: [[2, 3, 4]]<br />
Unknown.$collect(JsArrayString.java:42)<br/>
Unknown.fillInStackTrace_1(StackTraceCreator.java:174)<br/>
Unknown.fillInStackTrace(StackTraceCreator.java:508)<br/>
Unknown.$fillInStackTrace(Throwable.java:72)<br/>
Unknown.$$init_1152(Throwable.java:46)<br/>
Unknown.Throwable_1(Throwable.java:52)<br/>
Unknown.Exception_1(Exception.java:29)<br/>
Unknown.$callFailureCallback(NewVersionsResponse.java:142)<br/>
Unknown.apply_696(NewVersionsResponse.java:50)<br/>
Unknown.$doProcessResponsesFromServer(PullExecutor.java:122)<br/>
Unknown.$tick_1(SynchronizationProcess.java:221)<br/>
Unknown.$receiveFromServerOrCache(PullProcess.java:34)<br/>
Unknown.onNewVersions_2(PullVersionsHandler.java:38)<br/>
Unknown.onNewVersions_1(MessageSender.java:219)<br/>
Unknown.onNewVersions(NodeFilterIncomingConnection.java:83)<br/>
Unknown.onNewVersions(NodeFilterIncomingConnection.java:83)<br/>
Unknown.pushOn_7(PullVersionsResponseData.java:62)<br/>
Unknown.process_3(RemoteToLocalCallbackConverter.java:63)<br/>
Unknown.$processStepsGuarded(ThreadSpace.java:33)<br/>
Unknown.processSteps(ThreadSpace.java:54)<br/>
Unknown.$onSuccess_74(RemoteToLocalCallbackConverter.java:90)<br/>
Unknown.onSuccess_149(RemoteToLocalCallbackConverter.java:30)<br/>
Unknown.$onSuccess_71(InternalAuthorizingRemoteConnection.java:91)<br/>
Unknown.onSuccess_146(InternalAuthorizingRemoteConnection.java:87)<br/>
Unknown.process_1(CallbackSorter.java:73)<br/>
Unknown.$processItems(BetterAccessThreadImplementation.java:128)<br/>
Unknown.$run_0(BetterAccessThreadImplementation.java:115)<br/>
Unknown.run_63(BetterAccessThreadImplementation.java:79)<br/>
Unknown.execute_10(GwtConcurrencyImpl.java:133)<br/>
Unknown.$runProtected(BetterAccessThreadImplementation.java:74)<br/>
Unknown.$startIfRequired(BetterAccessThreadImplementation.java:59)<br/>
Unknown.processSteps_0(BetterAccessThreadImplementation.java:390)<br/>
Unknown.$attemptToExecuteCallback(CallbackSorter.java:86)<br/>
Unknown.$onSuccess_62(CallbackSorter.java:125)<br/>
Unknown.onSuccess_131(CallbackSorter.java:112)<br/>
Unknown.$executeCallback(ClientThreadSynchronizedConnection.java:74)<br/>
Unknown.$onSuccess_67(ClientThreadSynchronizedConnection.java:92)<br/>
Unknown.onSuccess_140(ClientThreadSynchronizedConnection.java:91)<br/>
Unknown.$onSuccess_68(CachePullUpdatesClientConnection.java:92)<br/>
Unknown.onSuccess_141(CachePullUpdatesClientConnection.java:63)<br/>
Unknown.$process_4(GwtRpcResponseReader.java:24)<br/>
Unknown.onResponseReceived_0(GwtHttpRemoteConnection.java:50)<br/>
Unknown.$fireOnResponseReceived(Request.java:258)<br/>
Unknown.onReadyStateChange(RequestBuilder.java:412)<br/>
Unknown.anonymous(XMLHttpRequest.java:351)<br/>
Unknown.apply_482(Impl.java:189)<br/>
Unknown.entry0(Impl.java:249)<br/>
Unknown.anonymous(Impl.java:70)<br/>
-end of stack trace
```

**Comment by mxro** [comment]
This is reported in **another window** after deployment is enabled for a Micro Service.

```
Exception reported: Received invalid new version from server with number [14].
  Error while applying to local network [Connection between nodes [Nx.reference(https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Admin/.n/Services1/.n/ObjectHub/deploy/main/~prod) -> One.value(deploy).at("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Admin/.n/Services1/.n/ObjectHub/deploy/main/~prod/deploy")] is already defined in network. Cannot append node.]
  Versions to be applied: [[14]]
```

**Comment by mxro** [comment]
Fixed in NewVersionsResponse.java: If connection already defined problem encounter, version from server will not be applied as a workaround.
