### ISSUE TITLE
Web Server becomes unresponsive when Micro Service fails

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#41]
# Steps

Create a Micro service that includes a syntax error, resulting in an error as the following:

```
2016-11-21T03:23:37.297Z	e397285f-af99-11e6-a390-1bda03c582b4	ReferenceError: elem is not defined
    at /var/task/index.js:147:93
    at cmpl_getSecret (/var/task/index.js:87:3)
    at init (/var/task/index.js:130:1)
    at exports.handler (/var/task/index.js:199:5)
```

--> This error is not reported correctly in ObjectHub Micro Service editor.

There it shows the following in the log:

```
2016-11-21T03:27:15.733Z	64e0d7ec-af9a-11e6-aea7-37bf19f385f4	{"errorMessage":"[object Object]"}
```

# Findings

The webserver becomes unresponsive. For many RPC calls, the following is triggered on the server:

```
delight.concurrency.jre.JavaExecutor$1@6818133b: Task exceeded timeout of 120000 ms (Task: de.mxro.httpserver.internal.services.ConcurrentWorkerThreadService$2@66dff048)
delight.concurrency.jre.JavaExecutor$1@60204e90: Task exceeded timeout of 120000 ms (Task: de.mxro.httpserver.internal.services.ConcurrentWorkerThreadService$2@6ee7bce4)
delight.concurrency.jre.JavaExecutor$1@39d3bdc: Task exceeded timeout of 120000 ms (Task: de.mxro.httpserver.internal.services.ConcurrentWorkerThreadService$2@d5ac5df)
delight.concurrency.jre.JavaExecutor$1@5382f597: Task exceeded timeout of 120000 ms (Task: de.mxro.httpserver.internal.services.ConcurrentWorkerThreadService$2@5d450197)
delight.concurrency.jre.JavaExecutor$1@7303bfe0: Task exceeded timeout of 120000 ms (Task: de.mxro.httpserver.internal.services.ConcurrentWorkerThreadService$2@7dc45ff0)
delight.concurrency.jre.JavaExecutor$1@77ea8292: Task exceeded timeout of 120000 ms (Task: de.mxro.httpserver.internal.services.ConcurrentWorkerThreadService$2@792d621f)
delight.concurrency.jre.JavaExecutor$1@415bf41e: Task exceeded timeout of 120000 ms (Task: de.mxro.httpserver.internal.services.ConcurrentWorkerThreadService$2@4f9c1245)
delight.concurrency.jre.JavaExecutor$1@266cd1e2: Task exceeded timeout of 120000 ms (Task: de.mxro.httpserver.internal.services.ConcurrentWorkerThreadService$2@28ab2b5f)
delight.concurrency.jre.JavaExecutor$1@7f0acc5b: Task exceeded timeout of 120000 ms (Task: de.mxro.httpserver.internal.services.ConcurrentWorkerThreadService$2@71cd3dca)
```

**Comment by objecthub-io** [comment]
Seems not to happen anymore.
