### ISSUE TITLE
Server sometimes stops on HookConnection Timeout

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#42]
Stack trace from server:

```
Operation [com.appjangle.database.hooks.HookConnection$2@6c883fe2] timed out. (from object: com.appjangle.database.hooks.HookConnection$1@204cc68a)
java.lang.Exception: Operation [com.appjangle.database.hooks.HookConnection$2@6c883fe2] timed out.
  delight.concurrency.schedule.SequentialOperationScheduler$5$1.run(SequentialOperationScheduler.java:281)
  delight.concurrency.jre.JavaExecutor$2.run(JavaExecutor.java:41)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
Operation [com.appjangle.database.hooks.HookConnection$2@367f1fa7] timed out. (from object: com.appjangle.database.hooks.HookConnection$1@313a272a)
java.lang.Exception: Operation [com.appjangle.database.hooks.HookConnection$2@367f1fa7] timed out.
  delight.concurrency.schedule.SequentialOperationScheduler$5$1.run(SequentialOperationScheduler.java:281)
  delight.concurrency.jre.JavaExecutor$2.run(JavaExecutor.java:41)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
Exception in thread "delight.concurrency.schedule.SequentialOperationScheduler" java.lang.RuntimeException: Operation [com.appjangle.database.hooks.HookConnection$2@6c883fe2] failed. Callback cannot be triggered, it was already triggered.
	at delight.concurrency.schedule.SequentialOperationScheduler$3$1.run(SequentialOperationScheduler.java:204)
	at delight.concurrency.jre.JavaExecutor$2.run(JavaExecutor.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Operation [com.appjangle.database.hooks.internal.VersionDb$1@4292c8b6] timed out.
	at delight.concurrency.schedule.SequentialOperationScheduler$5$1.run(SequentialOperationScheduler.java:281)
	... 4 more
```

**Comment by objecthub-io** [comment]
Error reported on client (might be related):

```
Versioning conflict on server and client. From client: [658618] On Server: [658623]
```

**Comment by objecthub-io** [comment]
This does not appear to be happening anymore.
