### ISSUE TITLE
Synchronization Error: 'Only the last version for a node should be reverted.'

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#44]
When a synchronization requires to revert local nodes (e.g. parent node changed on another client), sometimes the following error occurs:

```
Exception in thread "delight.concurrency.schedule.BetterAccessThreadImplementation" java.lang.AssertionError: Only the last version for a node should be reverted.
  Node: [Nx.reference(http://localhost:80/main/~testdb/node22)]
  Version to be reverted: [http://localhost/internal/versions/http_/localhost:80/main/~testdb/_node22/5]
  Last version in network: [http://localhost/internal/versions/http_/localhost:80/main/~testdb/_node22/12]
	at nx.sync.internal.syncworker.SynchronizationProcess.revertLocalVersionSafe(SynchronizationProcess.java:382)
	at nx.sync.internal.syncworker.revert.RevertExecutor.revertVersion(RevertExecutor.java:72)
	at nx.sync.internal.syncworker.revert.RevertExecutor.doRevertedTemporarily(RevertExecutor.java:61)
	at nx.sync.internal.syncworker.SynchronizationProcess.tick(SynchronizationProcess.java:159)
	at nx.sync.internal.syncworker.SynchronizationProcess$2.onSuccess(SynchronizationProcess.java:178)
	at nx.sync.internal.syncworker.commit.CommitExecutor$1.onCompleted(CommitExecutor.java:67)
	at delight.async.flow.CallbackLatch.registerSuccess(CallbackLatch.java:41)
	at nx.sync.internal.syncworker.commit.CommitExecutor$2.onSuccess(CommitExecutor.java:84)
	at nx.sync.internal.syncworker.commit.CommitExecutor$3.onSuccess(CommitExecutor.java:103)
	at nx.sync.internal.syncworker.handler.commit.operations.SuccessfullyCommittedResponse.apply(SuccessfullyCommittedResponse.java:36)
	at nx.sync.internal.syncworker.commit.CommitExecutor.processResult(CommitExecutor.java:98)
	at nx.sync.internal.syncworker.commit.CommitExecutor.doProcessResponses(CommitExecutor.java:80)
	at nx.sync.internal.syncworker.SynchronizationProcess.tick(SynchronizationProcess.java:173)
	at nx.sync.internal.syncworker.SynchronizationProcess.receiveFromServer(SynchronizationProcess.java:322)
	at nx.sync.internal.syncworker.commit.CommitHandler$CommitCallback.onSuccess(CommitHandler.java:63)
	at nx.sync.internal.syncworker.cache.MessageSender$CacheCommittCallback.onSuccess(MessageSender.java:67)
	at nx.remote.messages.v01.CommitResponseData.pushOn(CommitResponseData.java:63)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter$1.process(RemoteToLocalCallbackConverter.java:63)
	at delight.concurrency.schedule.ThreadSpace.processStepsGuarded(ThreadSpace.java:33)
	at delight.concurrency.schedule.ThreadSpace.processSteps(ThreadSpace.java:54)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onSuccess(RemoteToLocalCallbackConverter.java:90)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onSuccess(RemoteToLocalCallbackConverter.java:1)
	at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onSuccess(InternalAuthorizingRemoteConnection.java:91)
	at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onSuccess(InternalAuthorizingRemoteConnection.java:1)
	at mx.gwtutils.async.CallbackSorter$1.process(CallbackSorter.java:73)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:128)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:115)
	at delight.concurrency.schedule.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:79)
	at delight.concurrency.jre.JavaExecutor$1.run(JavaExecutor.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Happens sometimes in test case TestConcurrentOperationsWithGcAndLocalStorage.

**Comment by objecthub-io** [comment]
Fixed.

Gave higher priority in synchronisation process to revert commits.
