### ISSUE TITLE
Exception on closing client in Java

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#50]
When an (uncached) client is closed on Java, sometimes the following exception is shown:

```
Exception in thread "class delight.keyvalue.jre.internal.SplitWorkerThreadsMapConnection$8->worker" java.lang.RuntimeException: Thread executor could not execute: [delight.concurrency.jre.JavaExecutor$3@76b20547]. 
  Executor: [java.util.concurrent.ThreadPoolExecutor@ee9315c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]]
  Thread owner: [delight.keyvalue.internal.decorators.EnforceAsynchronousPutStoreNew@378bf509->forStore:delight.keyvalue.jre.internal.SplitWorkerThreadsMapConnection@5fd0d5ae]
	at delight.concurrency.jre.JreConcurrency$5.rejectedExecution(JreConcurrency.java:240)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at delight.concurrency.jre.JavaExecutor.execute(JavaExecutor.java:45)
	at delight.concurrency.schedule.SequentialOperationScheduler$5.onSuccess(SequentialOperationScheduler.java:253)
	at delight.keyvalue.internal.decorators.EnforceAsynchronousPutStoreNew$5.onSuccess(EnforceAsynchronousPutStoreNew.java:140)
	at delight.keyvalue.internal.decorators.EnforceAsynchronousPutStoreNew$5.onSuccess(EnforceAsynchronousPutStoreNew.java:1)
	at delight.async.flow.CallbackMap$1.onSuccess(CallbackMap.java:50)
	at delight.async.AsyncCommon$3.onSuccess(AsyncCommon.java:120)
	at nx.persistence.nio.internal.FileStore.put(FileStore.java:48)
	at nx.persistence.nio.internal.FileStore.put(FileStore.java:1)
	at com.appjangle.client.internal.compression.ValueAndContextFilterMap.put(ValueAndContextFilterMap.java:19)
	at delight.keyvalue.jre.internal.SplitWorkerThreadsMapConnection.writeValue(SplitWorkerThreadsMapConnection.java:50)
	at delight.keyvalue.jre.internal.SplitWorkerThreadsMapConnection.access$0(SplitWorkerThreadsMapConnection.java:31)
	at delight.keyvalue.jre.internal.SplitWorkerThreadsMapConnection$2.run(SplitWorkerThreadsMapConnection.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by objecthub-io** [comment]
No, seems to occur for cached clients.

Values should be written to cache during session.

**Comment by objecthub-io** [comment]
Fixed.
