### ISSUE TITLE
Sql Store Times out

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#51]
The following exception is reported. Afterwards, the server stops:

```
com.appjangle.database.internal.databases.MainNodeDatabaseRepository$6$1@7c38d123: Database data successfully deleted *12604 for objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Lists/.n/Inline_List__MA_/.meta/navparent
com.appjangle.sql.core.internal.TableManager@52cc2f5: get databases https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Lists/.n/Inline_List__MA_/.meta/navparent/~*0
com.appjangle.sql.core.internal.TableManager@52cc2f5: get all child database objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Lists/.n/Inline_List__MA_/.meta/navparent/~*0/
com.appjangle.sql.core.internal.TableManager@52cc2f5: got child databases []
com.appjangle.database.internal.databases.MainNodeDatabaseRepository@5d8d50be: Check if node has databases objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Lists/.n/Inline_List__MA_/.meta/owner/objecth1
Exception in thread "de.mxro.async.map.sql.internal.SqlStoreImplementation@de3a06f->jdbc:mysql://localhost/java?user=XXX&password=XXX" java.lang.RuntimeException: java.lang.RuntimeException: com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
	at delight.concurrency.schedule.SingleInstanceQueueWorker$2.onFailure(SingleInstanceQueueWorker.java:73)
	at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:94)
	at delight.concurrency.schedule.SequentialOperationScheduler$6.run(SequentialOperationScheduler.java:280)
	at delight.concurrency.jre.JavaExecutor$3.run(JavaExecutor.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
	at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.processItems(SqlStoreImplementation.java:104)
	at delight.concurrency.schedule.SingleInstanceQueueWorker.perfomActions(SingleInstanceQueueWorker.java:94)
	at delight.concurrency.schedule.SingleInstanceQueueWorker.access$100(SingleInstanceQueueWorker.java:20)
	at delight.concurrency.schedule.SingleInstanceQueueWorker$1.apply(SingleInstanceQueueWorker.java:54)
	at delight.concurrency.schedule.SequentialOperationScheduler.executeOperation(SequentialOperationScheduler.java:212)
	at delight.concurrency.schedule.SequentialOperationScheduler.executeWithTimeout(SequentialOperationScheduler.java:168)
	at delight.concurrency.schedule.SequentialOperationScheduler.access$000(SequentialOperationScheduler.java:21)
	at delight.concurrency.schedule.SequentialOperationScheduler$2.run(SequentialOperationScheduler.java:149)
	... 4 more
Caused by: com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2352)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.performInsertOrUpdate(SqlStoreImplementation.java:247)
	at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.writeToSqlDatabase(SqlStoreImplementation.java:144)
	at de.mxro.async.map.sql.internal.SqlStoreImplementation$WriteWorker.processItems(SqlStoreImplementation.java:102)
	... 11 more
Client disconnected before response was sent.

```

**Comment by objecthub-io** [comment]
Modified processItems so that on an exception the exception callback is called.

**Comment by stellardb** [comment]
Does not seem to appear anymore.
