### ISSUE TITLE
Server becomes unresponsive after exception in SQL replication

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#56]
When an exception occurs in SQL replication, the server becomes unresponsive and does not respond, for instance, to LoginWithSessionID messages.

Exception reported in SQL replication:

```
Exception in thread "nx.remote.internal.connections.SingleConcurrentOperationConnection@40d35c28->forConnection:com.appjangle.database.internal.connections.ExceptionWrappingConnection@1583257" java.lang.ClassCastException: com.ononedb.nextweb.nodes.OnedbPort cannot be cast to java.lang.Boolean
	at com.appjangle.sql.core.internal.SqlTypes.getStringValue(SqlTypes.java:133)
	at com.appjangle.sql.core.internal.SqlImplConnection.update(SqlImplConnection.java:95)
	at com.appjangle.sql.core.internal.FieldOperationExecutor$7$1$1.apply(FieldOperationExecutor.java:499)
	at com.appjangle.sql.core.internal.FieldOperationExecutor$7$1$1.apply(FieldOperationExecutor.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at com.appjangle.sql.core.internal.TableManager.assertField(TableManager.java:468)
	at com.appjangle.sql.core.internal.FieldOperationExecutor$7$1.apply(FieldOperationExecutor.java:520)
	at delight.concurrency.Concurrent.sequentialInt(Concurrent.java:122)
	at delight.concurrency.Concurrent.sequential(Concurrent.java:28)
	at com.appjangle.sql.core.internal.FieldOperationExecutor$7.apply(FieldOperationExecutor.java:537)
	at com.appjangle.sql.core.internal.FieldOperationExecutor$7.apply(FieldOperationExecutor.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at com.appjangle.sql.core.internal.TableManager$1.apply(TableManager.java:80)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:65)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:12)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:8)
	at com.appjangle.sql.core.internal.TableManager.assertTablesForDbAndParentDbs(TableManager.java:108)
	at com.appjangle.sql.core.internal.TableManager.access$0(TableManager.java:64)
	at com.appjangle.sql.core.internal.TableManager$1.apply(TableManager.java:85)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:65)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:12)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:8)
	at com.appjangle.sql.core.internal.TableManager.assertTablesForDbAndParentDbs(TableManager.java:108)
	at com.appjangle.sql.core.internal.TableManager.access$0(TableManager.java:64)
	at com.appjangle.sql.core.internal.TableManager$1.apply(TableManager.java:85)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:65)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:12)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:8)
	at com.appjangle.sql.core.internal.TableManager.assertTablesForDbAndParentDbs(TableManager.java:108)
	at com.appjangle.sql.core.internal.TableManager.access$0(TableManager.java:64)
	at com.appjangle.sql.core.internal.TableManager$1$1.apply(TableManager.java:100)
	at com.appjangle.sql.core.internal.TableManager$1$1.apply(TableManager.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at com.appjangle.sql.core.internal.TableManager$2$1.apply(TableManager.java:129)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:68)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:12)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:8)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:12)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:8)
	at com.appjangle.sql.core.internal.TableManager$2.apply(TableManager.java:136)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:68)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:12)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:8)
	at com.appjangle.sql.core.internal.TableManager.assertTable(TableManager.java:143)
	at com.appjangle.sql.core.internal.TableManager.access$1(TableManager.java:111)
	at com.appjangle.sql.core.internal.TableManager$1.apply(TableManager.java:104)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:68)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:12)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:8)
	at com.appjangle.sql.core.internal.TableManager.assertTablesForDbAndParentDbs(TableManager.java:108)
	at com.appjangle.sql.core.internal.TableManager.assertTables(TableManager.java:61)
	at com.appjangle.sql.core.internal.FieldOperationExecutor.writeAttribute(FieldOperationExecutor.java:541)
	at com.appjangle.sql.core.internal.FieldOperationExecutor.access$1(FieldOperationExecutor.java:462)
	at com.appjangle.sql.core.internal.FieldOperationExecutor$6$1$3.apply(FieldOperationExecutor.java:403)
	at com.appjangle.sql.core.internal.FieldOperationExecutor$6$1$3.apply(FieldOperationExecutor.java:1)
	at delight.promise.internal.PromiseImpl$3.onSuccess(PromiseImpl.java:216)
	at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:141)
	at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
	at com.ononedb.nextweb.OnedbLink$1$1.thenDo(OnedbLink.java:103)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1.onSuccess(LoadAndSynchronizeOperation.java:67)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:237)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:165)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:53)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:1)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
	at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:90)
	at com.ononedb.nextweb.OnedbLink$1.apply(OnedbLink.java:99)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:48)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:87)
	at delight.promise.internal.PromiseImpl.get(PromiseImpl.java:184)
	at io.nextweb.promise.DataPromiseImpl.get(DataPromiseImpl.java:33)
	at com.ononedb.nextweb.OnedbLink.get(OnedbLink.java:234)
	at com.appjangle.sql.core.internal.FieldOperationExecutor$6$1.apply(FieldOperationExecutor.java:406)
	at delight.concurrency.Concurrent.sequentialInt(Concurrent.java:122)
	at delight.concurrency.Concurrent.sequential(Concurrent.java:28)
	at com.appjangle.sql.core.internal.FieldOperationExecutor$6$3.apply(FieldOperationExecutor.java:453)
	at com.appjangle.sql.core.internal.FieldOperationExecutor$6$3.apply(FieldOperationExecutor.java:1)
	at delight.promise.internal.PromiseImpl$3.onSuccess(PromiseImpl.java:216)
	at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:141)
	at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
	at com.appjangle.api.queries.Queries$4$3$1$2.apply(Queries.java:298)
	at com.appjangle.api.queries.Queries$4$3$1$2.apply(Queries.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at delight.async.flow.CallbackAggregator$1.onSuccess(CallbackAggregator.java:73)
	at com.appjangle.api.queries.Queries$4$3$1$1$3$2.apply(Queries.java:274)
	at com.appjangle.api.queries.Queries$4$3$1$1$3$2.apply(Queries.java:1)
	at delight.promise.internal.PromiseImpl$3.onSuccess(PromiseImpl.java:216)
	at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:141)
	at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1$1$2.thenDo(P_Entity_Select.java:310)
	at one.engine.nx.internal.operations.SelectNodesOperation$1.thenDo(SelectNodesOperation.java:77)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1.onSuccess(LoadAndSynchronizeOperation.java:67)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$3.onSuccess(LoadAndSynchronizeOperation.java:262)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$3.onSuccess(LoadAndSynchronizeOperation.java:1)
	at delight.async.flow.CallbackMap$1.onSuccess(CallbackMap.java:50)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$4.onSuccess(LoadAndSynchronizeOperation.java:282)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:237)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:165)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:276)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:165)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:53)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:1)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
	at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:90)
	at one.engine.nx.internal.operations.SelectNodesOperation.execute(SelectNodesOperation.java:34)
	at one.engine.nx.internal.operations.SelectNodesOperation.execute(SelectNodesOperation.java:1)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.select.SelectChildrenWithQueryGrammar.and(SelectChildrenWithQueryGrammar.java:28)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1$1.run(P_Entity_Select.java:296)
	at one.engine.nx.internal.ClientWrapper$5.process(ClientWrapper.java:197)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:129)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:116)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.runProtected(BetterAccessThreadImplementation.java:83)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.access$0(BetterAccessThreadImplementation.java:63)
	at delight.concurrency.schedule.BetterAccessThreadImplementation$2.notifiyFinished(BetterAccessThreadImplementation.java:88)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:121)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.runProtected(BetterAccessThreadImplementation.java:83)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.access$0(BetterAccessThreadImplementation.java:63)
	at delight.concurrency.schedule.BetterAccessThreadImplementation$2.notifiyFinished(BetterAccessThreadImplementation.java:88)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:121)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.runProtected(BetterAccessThreadImplementation.java:83)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.access$0(BetterAccessThreadImplementation.java:63)
	at delight.concurrency.schedule.BetterAccessThreadImplementation$2.notifiyFinished(BetterAccessThreadImplementation.java:88)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:121)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.runProtected(BetterAccessThreadImplementation.java:83)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.access$0(BetterAccessThreadImplementation.java:63)
	at delight.concurrency.schedule.BetterAccessThreadImplementation$2.notifiyFinished(BetterAccessThreadImplementation.java:88)

```

**Comment by mxro** [comment]
Fixed.
