### ISSUE TITLE
Client attempts to reduce version number of last synchronized version.

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#58]
Error during synchronisation, esp test case TestComplexHookOnServer.

Exceptions reported:

```
Exception in thread "delight.concurrency.schedule.BetterAccessThreadImplementation@8576fa0" java.lang.AssertionError: Client attempts to reduce version number of last synchronized version.
  Node has been received: [true]
  Version number in cache: [26]
  Version number to be set: [3]
  For node: [Nx.reference(http://localhost:80/hooktest/.n)]
  Version to be injected: [nx.versions.nodes.v01.ChainedVersionData@76897ffc[statement=ForManagedNetwork.do(ForNetwork.append(One.value(folder).at("http://localhost:80/hooktest/.n/folder2")).to(Nx.reference(http://localhost:80/hooktest/.n))), NxVersions.aVersion().atUri(https://v.localhost:80/hooktest/http_/localhost:80/hooktest/_.n/3).withVersionNumber(3).andPreviousVersion(Nx.reference(https://v.localhost:80/hooktest/http_/localhost:80/hooktest/_.n/2))]]
  Local received version: [nx.versions.nodes.v01.ChainedVersionData@b31915b0[statement=ForManagedNetwork.do(nx.core.statements.v01.LeaveUnchangedStatement@1), NxVersions.aVersion().atUri(https://v.localhost:80/hooktest/http_/localhost:80/hooktest/_.n/26).withVersionNumber(26).andPreviousVersion(Nx.reference(https://v.localhost:80/hooktest/http_/localhost:80/hooktest/_.n/25))]]
	at nx.sync.internal.syncworker.cache.SyncCache.setLatestVersionSynchronizedFromServer(SyncCache.java:79)
	at nx.sync.internal.syncworker.pull.operations.NewVersionsResponse.apply(NewVersionsResponse.java:85)
	at nx.sync.internal.syncworker.pull.PullExecutor.doProcessResponsesFromServer(PullExecutor.java:122)
	at nx.sync.internal.syncworker.SynchronizationProcess.tick(SynchronizationProcess.java:225)
	at nx.sync.internal.syncworker.pull.PullProcess.receiveFromServerOrCache(PullProcess.java:34)
	at nx.sync.internal.syncworker.pull.PullVersionsHandler$PullVersionsCallbackHandler.onUnchanged(PullVersionsHandler.java:62)
	at nx.sync.internal.syncworker.cache.MessageSender$CacheReceiveCallback.onUnchanged(MessageSender.java:241)
	at nx.filter.internal.NodeFilterIncomingConnection$1.onUnchanged(NodeFilterIncomingConnection.java:88)
	at nx.filter.internal.NodeFilterIncomingConnection$1.onUnchanged(NodeFilterIncomingConnection.java:88)
	at nx.remote.messages.v03.PullVersionsResponseData.pushOn(PullVersionsResponseData.java:64)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter$1.process(RemoteToLocalCallbackConverter.java:63)
	at delight.concurrency.schedule.ThreadSpace.processStepsGuarded(ThreadSpace.java:33)
	at delight.concurrency.schedule.ThreadSpace.processSteps(ThreadSpace.java:54)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onSuccess(RemoteToLocalCallbackConverter.java:90)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onSuccess(RemoteToLocalCallbackConverter.java:1)
	at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onSuccess(InternalAuthorizingRemoteConnection.java:91)
	at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onSuccess(InternalAuthorizingRemoteConnection.java:1)
	at mx.gwtutils.async.CallbackSorter$1.process(CallbackSorter.java:73)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:128)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:115)
	at delight.concurrency.schedule.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:78)
	at delight.concurrency.jre.JavaExecutor$3.run(JavaExecutor.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


Exception in thread "delight.concurrency.schedule.BetterAccessThreadImplementation@482f8f11" java.lang.AssertionError: Client attempts to reduce version number of last synchronized version.
  Node has been received: [true]
  Version number in cache: [4]
  Version number to be set: [2]
  For node: [One.value(folder).at("http://localhost:80/hooktest/.n/folder26")]
  Version to be injected: [nx.versions.nodes.v01.ChainedVersionData@7f081892[statement=ForManagedNetwork.do(ForNetwork.replace().node(One.value(folder).at("http://localhost:80/hooktest/.n/folder26")).with(One.value(The folder).at("http://localhost:80/hooktest/.n/folder26"))), NxVersions.aVersion().atUri(https://v.localhost:80/hooktest/http_/localhost:80/hooktest/.n/_folder26/2).withVersionNumber(2).andPreviousVersion(Nx.reference(http://www.linnk.de/s/initialversion))]]
  Local received version: [nx.versions.nodes.v01.ChainedVersionData@cfc29af6[statement=ForManagedNetwork.do(nx.core.statements.v01.LeaveUnchangedStatement@1), NxVersions.aVersion().atUri(https://v.localhost:80/hooktest/http_/localhost:80/hooktest/.n/_folder26/4).withVersionNumber(4).andPreviousVersion(Nx.reference(https://v.localhost:80/hooktest/http_/localhost:80/hooktest/.n/_folder26/3))]]
	at nx.sync.internal.syncworker.cache.SyncCache.setLatestVersionSynchronizedFromServer(SyncCache.java:79)
	at nx.sync.internal.syncworker.pull.operations.NewVersionsResponse.apply(NewVersionsResponse.java:85)
	at nx.sync.internal.syncworker.pull.PullExecutor.doProcessResponsesFromServer(PullExecutor.java:122)
	at nx.sync.internal.syncworker.SynchronizationProcess.tick(SynchronizationProcess.java:225)
	at nx.sync.internal.syncworker.pull.PullProcess.receiveFromServerOrCache(PullProcess.java:34)
	at nx.sync.internal.syncworker.pull.ResolveHandler$1.onResolve(ResolveHandler.java:36)
	at nx.sync.internal.syncworker.cache.MessageSender$CacheResolveCallback.onResolve(MessageSender.java:282)
	at nx.filter.internal.NodeFilterIncomingConnection$2.onResolve(NodeFilterIncomingConnection.java:117)
	at nx.filter.internal.NodeFilterIncomingConnection$2.onResolve(NodeFilterIncomingConnection.java:117)
	at nx.remote.messages.v01.ResolveResponseData.pushOn(ResolveResponseData.java:77)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter$1.process(RemoteToLocalCallbackConverter.java:63)
	at delight.concurrency.schedule.ThreadSpace.processStepsGuarded(ThreadSpace.java:33)
	at delight.concurrency.schedule.ThreadSpace.processSteps(ThreadSpace.java:54)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onSuccess(RemoteToLocalCallbackConverter.java:90)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onSuccess(RemoteToLocalCallbackConverter.java:1)
	at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onSuccess(InternalAuthorizingRemoteConnection.java:91)
	at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onSuccess(InternalAuthorizingRemoteConnection.java:1)
	at mx.gwtutils.async.CallbackSorter$1.process(CallbackSorter.java:73)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:128)
	at delight.concurrency.schedule.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:115)
	at delight.concurrency.schedule.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:78)
	at delight.concurrency.jre.JavaExecutor$3.run(JavaExecutor.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stellardb** [comment]
Exception still occurs:

```
Exception in thread "delight.scheduler.BetterAccessThreadImplementation@5d721fe7" java.lang.AssertionError: Client attempts to reduce version number of last synchronized version.
  Node has been received: [true]
  Version number in cache: [4]
  Version number to be set: [2]
  For node: [One.value(folder).at("http://localhost:80/hooktest/.n/folder32")]
  Version to be injected: [nx.versions.nodes.v01.ChainedVersionData@3a985c88[statement=ForManagedNetwork.do(ForNetwork.replace().node(One.value(folder).at("http://localhost:80/hooktest/.n/folder32")).with(One.value(The folder).at("http://localhost:80/hooktest/.n/folder32"))), NxVersions.aVersion().atUri(https://v.localhost:80/hooktest/http_/localhost:80/hooktest/.n/_folder32/2).withVersionNumber(2).andPreviousVersion(Nx.reference(http://www.linnk.de/s/initialversion))]]
  Local received version: [nx.versions.nodes.v01.ChainedVersionData@9516a8cc[statement=ForManagedNetwork.do(nx.core.statements.v01.LeaveUnchangedStatement@1), NxVersions.aVersion().atUri(https://v.localhost:80/hooktest/http_/localhost:80/hooktest/.n/_folder32/4).withVersionNumber(4).andPreviousVersion(Nx.reference(https://v.localhost:80/hooktest/http_/localhost:80/hooktest/.n/_folder32/3))]]
	at nx.sync.internal.syncworker.cache.SyncCache.setLatestVersionSynchronizedFromServer(SyncCache.java:79)
	at nx.sync.internal.syncworker.pull.operations.NewVersionsResponse.apply(NewVersionsResponse.java:85)
	at nx.sync.internal.syncworker.pull.PullExecutor.doProcessResponsesFromServer(PullExecutor.java:122)
	at nx.sync.internal.syncworker.SynchronizationProcess.tick(SynchronizationProcess.java:225)
	at nx.sync.internal.syncworker.pull.PullProcess.receiveFromServerOrCache(PullProcess.java:34)
	at nx.sync.internal.syncworker.pull.PullVersionsHandler$PullVersionsCallbackHandler.onUnchanged(PullVersionsHandler.java:62)
	at nx.sync.internal.syncworker.cache.MessageSender$CacheReceiveCallback.onUnchanged(MessageSender.java:241)
	at nx.filter.internal.NodeFilterIncomingConnection$1.onUnchanged(NodeFilterIncomingConnection.java:88)
	at nx.filter.internal.NodeFilterIncomingConnection$1.onUnchanged(NodeFilterIncomingConnection.java:88)
	at nx.remote.messages.v03.PullVersionsResponseData.pushOn(PullVersionsResponseData.java:65)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter$1.process(RemoteToLocalCallbackConverter.java:63)
	at delight.concurrency.schedule.ThreadSpace.processStepsGuarded(ThreadSpace.java:33)
	at delight.concurrency.schedule.ThreadSpace.processSteps(ThreadSpace.java:54)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onSuccess(RemoteToLocalCallbackConverter.java:90)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onSuccess(RemoteToLocalCallbackConverter.java:1)
	at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onSuccess(InternalAuthorizingRemoteConnection.java:91)
	at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onSuccess(InternalAuthorizingRemoteConnection.java:1)
	at mx.gwtutils.async.CallbackSorter$1.process(CallbackSorter.java:73)
	at delight.scheduler.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:133)
	at delight.scheduler.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:120)
	at delight.scheduler.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:83)
	at delight.concurrency.jre.JavaExecutor$4.run(JavaExecutor.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stellardb** [comment]
Fixed SyncCache that instead of throwing an error, lower versions will simply not be stored.

This was probably caused by the PullVersionResponse having versions of it's children attached OR by the parallel storage triggered by a commit operation.
