### ISSUE TITLE
URIs with non-ASCII characters cause exception

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#7]
Steps
- Request a node from the server with an URI that contains a non-ASCII character

Findings

The server reports an SQL exception

```
Caused by: java.lang.RuntimeException: java.sql.SQLException: Illegal mix of collations (ascii_general_ci,IMPLICIT) and (latin1_swedish_ci,COERCIBLE) for operation '='
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.performGet(SqlStoreImplementation.java:384)
    at de.mxro.async.map.sql.internal.SqlStoreImplementation.getNode(SqlStoreImplementation.java:352)
    ... 85 more
Caused by: java.sql.SQLException: Illegal mix of collations (ascii_general_ci,IMPLICIT) and (latin1_swedish_ci,COERCIBLE) for operation '='
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
```

**Comment by mxro** [comment]
Fixed
