### ISSUE TITLE
Exception 'Only initialVersion should be stored as reference'

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#73]
Might be caused by frequent clearVersions() performed on node.

Error reported

```
Exception in thread "delight.scheduler.BetterAccessThreadImplementation@100d5166" java.lang.RuntimeException: java.lang.RuntimeException: Only initialVersion should be stored as reference: Nx.reference(https://v.objecthub.io/system-triggers/~*1/https_/objecthub.io/system-triggers/~*1/_lastFired/329)
	at nx.sync.internal.syncworker.cache.MessageSender$1.onFailure(MessageSender.java:347)
	at nx.remote.internal.wrapper.InternalRemoteConnectionWrapper$CommittCallbackOrchestrator.onFailure(InternalRemoteConnectionWrapper.java:540)
	at nx.remote.internal.wrapper.RemoteToLocalCallbackConverter.onFailure(RemoteToLocalCallbackConverter.java:119)
	at nx.remote.internal.connections.InternalAuthorizingRemoteConnection$1.onFailure(InternalAuthorizingRemoteConnection.java:117)
	at mx.gwtutils.async.CallbackSorter$1.process(CallbackSorter.java:81)
	at delight.scheduler.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:133)
	at delight.scheduler.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:120)
	at delight.scheduler.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:83)
	at delight.concurrency.jre.JavaExecutor$4.run(JavaExecutor.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Only initialVersion should be stored as reference: Nx.reference(https://v.objecthub.io/system-triggers/~*1/https_/objecthub.io/system-triggers/~*1/_lastFired/329)
	at nx.versions.internal.VersionManager.resolveVersionSafe(VersionManager.java:110)
	at nx.versions.internal.VersionManager.collectVersions(VersionManager.java:137)
	at nx.versions.internal.InternalVersionedNetwork.pullVersionsForNode(InternalVersionedNetwork.java:115)
	at nx.versions.NxVersions.clearVersions(NxVersions.java:86)
	at com.appjangle.database.network.internal.VersionedNetworkConnection.clearVersions(VersionedNetworkConnection.java:233)
	at nx.remote.messages.v01.ClearVersionsMessageData.doOn(ClearVersionsMessageData.java:24)
	at com.appjangle.database.network.internal.LocalConnectionClearVersionsWrapper.call(LocalConnectionClearVersionsWrapper.java:44)
	at nx.remote.utils.NxServerUtils.sendMessages2(NxServerUtils.java:142)
	at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:134)
	at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
	at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
	at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
	at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
	at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
	at nx.remote.utils.FilterRemoteConnectionCallbacks.call(FilterRemoteConnectionCallbacks.java:34)
	at nx.server.auth.internal.AuthorizingConnection.executeAuthorizedRequests(AuthorizingConnection.java:268)
	at nx.server.auth.internal.AuthorizingConnection.access$0(AuthorizingConnection.java:231)
	at nx.server.auth.internal.AuthorizingConnection$1.onSuccess(AuthorizingConnection.java:88)
	at nx.server.auth.internal.AuthorizingConnection$1.onSuccess(AuthorizingConnection.java:1)
	at nx.server.auth.internal.AuthorizingConnection$4.onSuccess(AuthorizingConnection.java:154)
	at nx.server.auth.internal.AuthorizingConnection$4.onSuccess(AuthorizingConnection.java:1)
	at delight.concurrency.Concurrent.sequentialInt(Concurrent.java:102)
	at delight.concurrency.Concurrent.access$100(Concurrent.java:13)
	at delight.concurrency.Concurrent$4.onSuccess(Concurrent.java:143)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:194)
	at nx.server.auth.internal.AuthorizingConnection.access$3(AuthorizingConnection.java:188)
	at nx.server.auth.internal.AuthorizingConnection$5.onAuthorized(AuthorizingConnection.java:205)
	at com.appjangle.database.internal.PreventRemovalOfNodesWithDatabases.authorize(PreventRemovalOfNodesWithDatabases.java:36)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:200)
	at nx.server.auth.internal.AuthorizingConnection.access$3(AuthorizingConnection.java:188)
	at nx.server.auth.internal.AuthorizingConnection$5.onAuthorized(AuthorizingConnection.java:205)
	at nx.server.auth.internal.policies.PreventChangingNodesForServerRootPolicy.authorize(PreventChangingNodesForServerRootPolicy.java:30)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:200)
	at nx.server.auth.internal.AuthorizingConnection.access$3(AuthorizingConnection.java:188)
	at nx.server.auth.internal.AuthorizingConnection$5.onAuthorized(AuthorizingConnection.java:205)
	at nx.server.auth.internal.policies.BlockPutsPolicy.authorize(BlockPutsPolicy.java:59)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:200)
	at nx.server.auth.internal.AuthorizingConnection.access$3(AuthorizingConnection.java:188)
	at nx.server.auth.internal.AuthorizingConnection$5.onAuthorized(AuthorizingConnection.java:205)
	at nx.server.auth.internal.policies.AppendRealmProtectionPolicy.authorize(AppendRealmProtectionPolicy.java:100)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:200)
	at nx.server.auth.internal.AuthorizingConnection.access$3(AuthorizingConnection.java:188)
	at nx.server.auth.internal.AuthorizingConnection$5.onAuthorized(AuthorizingConnection.java:205)
	at nx.server.auth.internal.TokenNodeAuthorizer.authorizeNode(TokenNodeAuthorizer.java:64)
	at nx.server.auth.internal.policies.TokenGuardPolicy.authorize(TokenGuardPolicy.java:61)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:200)
	at nx.server.auth.internal.AuthorizingConnection.verifyMessage(AuthorizingConnection.java:178)
	at nx.server.auth.internal.AuthorizingConnection.access$2(AuthorizingConnection.java:169)
	at nx.server.auth.internal.AuthorizingConnection$3.apply(AuthorizingConnection.java:144)
	at delight.concurrency.Concurrent.sequentialInt(Concurrent.java:122)
	at delight.concurrency.Concurrent.access$100(Concurrent.java:13)
	at delight.concurrency.Concurrent$4.onSuccess(Concurrent.java:143)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:194)
	at nx.server.auth.internal.AuthorizingConnection.access$3(AuthorizingConnection.java:188)
	at nx.server.auth.internal.AuthorizingConnection$5.onAuthorized(AuthorizingConnection.java:205)
	at com.appjangle.database.internal.PreventRemovalOfNodesWithDatabases.authorize(PreventRemovalOfNodesWithDatabases.java:29)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:200)
	at nx.server.auth.internal.AuthorizingConnection.access$3(AuthorizingConnection.java:188)
	at nx.server.auth.internal.AuthorizingConnection$5.onAuthorized(AuthorizingConnection.java:205)
	at nx.server.auth.internal.policies.PreventChangingNodesForServerRootPolicy.authorize(PreventChangingNodesForServerRootPolicy.java:23)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:200)
	at nx.server.auth.internal.AuthorizingConnection.access$3(AuthorizingConnection.java:188)
	at nx.server.auth.internal.AuthorizingConnection$5.onAuthorized(AuthorizingConnection.java:205)
	at nx.server.auth.internal.policies.BlockPutsPolicy.authorize(BlockPutsPolicy.java:59)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:200)
	at nx.server.auth.internal.AuthorizingConnection.access$3(AuthorizingConnection.java:188)
	at nx.server.auth.internal.AuthorizingConnection$5.onAuthorized(AuthorizingConnection.java:205)
	at nx.server.auth.internal.policies.AppendRealmProtectionPolicy.authorize(AppendRealmProtectionPolicy.java:100)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:200)
	at nx.server.auth.internal.AuthorizingConnection.access$3(AuthorizingConnection.java:188)
	at nx.server.auth.internal.AuthorizingConnection$5.onAuthorized(AuthorizingConnection.java:205)
	at nx.server.auth.internal.TokenNodeAuthorizer.authorizeNode(TokenNodeAuthorizer.java:64)
	at nx.server.auth.internal.policies.TokenGuardPolicy.authorize(TokenGuardPolicy.java:61)
	at nx.server.auth.internal.AuthorizingConnection.checkPolicies(AuthorizingConnection.java:200)
	at nx.server.auth.internal.AuthorizingConnection.verifyMessage(AuthorizingConnection.java:178)
	at nx.server.auth.internal.AuthorizingConnection.access$2(AuthorizingConnection.java:169)
	at nx.server.auth.internal.AuthorizingConnection$3.apply(AuthorizingConnection.java:144)
	at delight.concurrency.Concurrent.sequentialInt(Concurrent.java:122)
	at delight.concurrency.Concurrent.sequential(Concurrent.java:28)
	at nx.server.auth.internal.AuthorizingConnection.checkAuthorizations(AuthorizingConnection.java:150)
	at nx.server.auth.internal.AuthorizingConnection.call(AuthorizingConnection.java:77)
	at com.appjangle.database.network.internal.connections.CachePullUpdatesServerConnection.call(CachePullUpdatesServerConnection.java:150)
	at com.appjangle.database.internal.connections.TriggerConnection.call(TriggerConnection.java:28)
	at nx.remote.internal.connections.SingleConcurrentOperationConnection$1.apply(SingleConcurrentOperationConnection.java:30)
	at delight.scheduler.SequentialOperationScheduler.executeOperation(SequentialOperationScheduler.java:204)
	at delight.scheduler.SequentialOperationScheduler.executeWithTimeout(SequentialOperationScheduler.java:180)
	at delight.scheduler.SequentialOperationScheduler.performRun(SequentialOperationScheduler.java:163)
	at delight.scheduler.SequentialOperationScheduler.runIfRequired(SequentialOperationScheduler.java:140)
	at delight.scheduler.SequentialOperationScheduler.schedule(SequentialOperationScheduler.java:105)
	at nx.remote.internal.connections.SingleConcurrentOperationConnection.call(SingleConcurrentOperationConnection.java:25)
	at com.appjangle.database.internal.network.NetworkServerConnection.call(NetworkServerConnection.java:49)
	at com.appjangle.database.internal.connections.ConnectionForNetworkMessages$2.apply(ConnectionForNetworkMessages.java:193)
	at com.appjangle.database.internal.connections.ConnectionForNetworkMessages$2.apply(ConnectionForNetworkMessages.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:364)
	at com.appjangle.database.internal.network.NetworkConnectionCache.assertFor(NetworkConnectionCache.java:206)
	at com.appjangle.database.internal.connections.ConnectionForNetworkMessages.call(ConnectionForNetworkMessages.java:165)
	at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
	at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
	at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
	at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
	at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
	at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
	at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
	at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
	at com.appjangle.database.hooks.internal.InterceptUpdatesConnection.call(InterceptUpdatesConnection.java:67)
	at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:101)
	at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
	at nx.remote.internal.connections.SafeShutdownConnection.call(SafeShutdownConnection.java:29)
	at com.appjangle.database.internal.connections.DatabaseConnection.call(DatabaseConnection.java:80)
	at nx.remote.internal.connections.BlockShutdownOperationConnection.call(BlockShutdownOperationConnection.java:18)
	at nx.remote.internal.connections.IgnorePullCacheMessageConnection.call(IgnorePullCacheMessageConnection.java:21)
	at nx.remote.utils.NxServerUtils.sendMessages2(NxServerUtils.java:142)
	at nx.remote.utils.NxServerUtils.callAndJoin(NxServerUtils.java:134)
	at nx.remote.internal.connections.ForkingConnection.call(ForkingConnection.java:52)
	at one.client.jre.OneJre$2.call(OneJre.java:108)
	at nx.remote.connections.ClientThreadSynchronizedConnection.call(ClientThreadSynchronizedConnection.java:39)
	at nx.remote.internal.connections.IncomingCallbackLinearizer.call(IncomingCallbackLinearizer.java:43)
	at nx.remote.internal.connections.InternalAuthorizingRemoteConnection.call(InternalAuthorizingRemoteConnection.java:84)
	at nx.remote.internal.wrapper.InternalRemoteConnectionWrapper.executeSendCache(InternalRemoteConnectionWrapper.java:444)
	at nx.remote.internal.wrapper.InternalRemoteConnectionWrapper.sendCacheItems(InternalRemoteConnectionWrapper.java:415)
	at nx.remote.internal.wrapper.InternalRemoteConnectionWrapper.writeToServerUnprotected(InternalRemoteConnectionWrapper.java:374)
	at nx.remote.internal.wrapper.InternalRemoteConnectionWrapper.writeToServerUnprotected(InternalRemoteConnectionWrapper.java:361)
	at nx.remote.internal.wrapper.InternalRemoteConnectionWrapper.writeToServer(InternalRemoteConnectionWrapper.java:281)
	at nx.remote.internal.InternalRemoteConnectionFacade.writeToServer(InternalRemoteConnectionFacade.java:114)
	at nx.sync.internal.syncworker.cache.MessageSender.sendWriteMessagesToServer(MessageSender.java:343)
	at nx.sync.internal.syncworker.commit.CommitExecutor.doSent(CommitExecutor.java:46)
	at nx.sync.internal.syncworker.SynchronizationProcess.tick(SynchronizationProcess.java:158)
	at nx.sync.internal.syncworker.SynchronizationProcess.sendToServer(SynchronizationProcess.java:79)
	at nx.sync.internal.InternalSynchronizedNetwork$2.sendCommitMessagesToServer(InternalSynchronizedNetwork.java:184)
	at one.engine.nx.internal.operations.CommitOperation.execute(CommitOperation.java:30)
	at one.engine.nx.internal.operations.CommitOperation.execute(CommitOperation.java:1)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.CommitGrammar.and(CommitGrammar.java:21)
	at one.engine.nx.internal.operations.ClearVersionsOperation$2$2.run(ClearVersionsOperation.java:114)
	at one.engine.nx.internal.ClientWrapper$5.process(ClientWrapper.java:200)
	... 7 more

```

**Comment by objecthub-io** [comment]
Fixed bug in clearVersions - that versions for which previous version was modified were not commited to storage.

**Comment by stellardb** [comment]
Does not seem to appear anymore.
