### ISSUE TITLE
HookConnection sometimes times out

### ISSUE THREAD

**Issue by mxro** [stellardb/StellarDB#8]
Error on client

```
Unhandled exception caught by engine: Operation [com.appjangle.database.hooks.HookConnection$3@6d2826e4] timed out. from com.appjangle.api.hooks.internal.manager.HookManager$1$1@12ad0
0.js:114457 java.lang.Exception: Operation [com.appjangle.database.hooks.HookConnection$3@6d2826e4] timed out.<br />
Unknown.$collect(JsArrayString.java:42)<br/>
Unknown.fillInStackTrace_1(StackTraceCreator.java:174)<br/>
Unknown.fillInStackTrace(StackTraceCreator.java:508)<br/>
Unknown.$fillInStackTrace(Throwable.java:72)<br/>
Unknown.$$init_1133(Throwable.java:46)<br/>
Unknown.Throwable_0(Throwable.java:49)<br/>
Unknown.Exception_0(Exception.java:25)<br/>
Unknown.instantiate_471(Exception_FieldSerializer.java:16)<br/>
Unknown.$instantiate(SerializerBase.java:55)<br/>
Unknown.instantiate_606(SerializerBase.java:112)<br/>
Unknown.deserialize_614(ClientSerializationStreamReader.java:115)<br/>
Unknown.$readObject(AbstractSerializationStreamReader.java:119)<br/>
Unknown.read_5(StorageValueType.java:223)<br/>
Unknown.$deserialize_0(ServerStorageRPCSerializerImpl.java:68)<br/>
Unknown.$deserialize_2(GwtClientSerializer.java:31)<br/>
Unknown.$process_4(GwtRpcResponseReader.java:37)<br/>
Unknown.onResponseReceived_0(GwtHttpRemoteConnection.java:50)<br/>
Unknown.$fireOnResponseReceived(Request.java:258)<br/>
Unknown.onReadyStateChange(RequestBuilder.java:412)<br/>
Unknown.anonymous(XMLHttpRequest.java:351)<br/>
Unknown.apply_480(Impl.java:189)<br/>
Unknown.entry0(Impl.java:249)<br/>
Unknown.anonymous(Impl.java:70)<br/>
-end of stack trace
0.js:71691 Uncaught java.lang.RuntimeException: java.lang.Exception: Operation [com.appjangle.database.hooks.HookConnection$3@6d2826e4] timed out
```

**Comment by mxro** [comment]
Error on server

```
com.appjangle.database.hooks.HookConnection@39da370: Processing change ChildAddedChangeData [childValue=]
Exception in thread "JreConcurrency-SimpleTimer-for-class delight.concurrency.schedule.SequentialOperationScheduler$4" java.lang.RuntimeException: java.lang.Exception: Operation [com.appjangle.database.hooks.HookConnection$2@3611abb2] timed out.
    at com.appjangle.database.hooks.HookConnection$1.onFailure(HookConnection.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$4.run(SequentialOperationScheduler.java:260)
    at delight.concurrency.jre.JreConcurrency$2$1.run(JreConcurrency.java:108)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.Exception: Operation [com.appjangle.database.hooks.HookConnection$2@3611abb2] timed out.
    at delight.concurrency.schedule.SequentialOperationScheduler$4.run(SequentialOperationScheduler.java:259)
    ... 3 more
```

**Comment by mxro** [comment]
Error on server

```
Exception in thread "JreConcurrency-SimpleTimer-for-class delight.concurrency.schedule.SequentialOperationScheduler$4" java.lang.RuntimeException: Operation [com.appjangle.database.hooks.internal.VersionDb$1@2388c0c5] failed. Callback cannot be triggered, it was already triggered.
    at delight.concurrency.schedule.SequentialOperationScheduler$3.onFailure(SequentialOperationScheduler.java:198)
    at delight.async.AsyncCommon$10.onFailure(AsyncCommon.java:318)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$4.run(SequentialOperationScheduler.java:260)
    at delight.concurrency.jre.JreConcurrency$2$1.run(JreConcurrency.java:108)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.Exception: Operation [com.appjangle.persistence.database.internal.SingleThreadDatabase$1@5c558939] timed out.
    at delight.concurrency.schedule.SequentialOperationScheduler$4.run(SequentialOperationScheduler.java:259)
    ... 3 more
```

**Comment by mxro** [comment]
First error on server

```
com.appjangle.database.hooks.HookConnection@39da370: Processing change ChildAddedChangeData [childValue=]
com.appjangle.database.hooks.HookConnection@39da370: Processing change com.appjangle.messages.hook.changes.v01.ValueChangedChangeData@4b0edae8Exception in thread "JreConcurrency-SimpleTimer-for-class delight.concurrency.schedule.SequentialOperationScheduler$4" 
java.lang.RuntimeException: java.lang.Exception: Operation [com.appjangle.persistence.database.internal.SingleThreadDatabase$1@3e9c92f0] timed out.
    at com.appjangle.database.hooks.HookConnection$1.onFailure(HookConnection.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$3.onFailure(SequentialOperationScheduler.java:205)
    at delight.async.AsyncCommon$10.onFailure(AsyncCommon.java:318)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$3.onFailure(SequentialOperationScheduler.java:205)
    at delight.async.AsyncCommon$10.onFailure(AsyncCommon.java:318)
    at delight.concurrency.schedule.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:88)
    at delight.concurrency.schedule.SequentialOperationScheduler$4.run(SequentialOperationScheduler.java:260)
    at delight.concurrency.jre.JreConcurrency$2$1.run(JreConcurrency.java:108)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.Exception: Operation [com.appjangle.persistence.database.internal.SingleThreadDatabase$1@3e9c92f0] timed out.
    at delight.concurrency.schedule.SequentialOperationScheduler$4.run(SequentialOperationScheduler.java:259)
    ... 3 more
```

**Comment by mxro** [comment]
Server side log

```
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@56c59e82
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@444dc9a2
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@38e3a25b
com.appjangle.database.hooks.HookConnection@229cf626: Notify updates.
                      Hook id: skz73qxz52lnzdp
                      Most recent server version notified for hook: 6410
                      Last synced with client version: 6406
                      Last received by client: 6406
com.appjangle.database.hooks.HookConnection@229cf626: Notify updates.
                      Hook id: 8y5sf3j5pswon2p
                      Most recent server version notified for hook: 6410
                      Last synced with client version: 6406
                      Last received by client: 6406
com.appjangle.database.hooks.HookConnection@229cf626: Notify updates.
                      Hook id: u1me54gxs7sspra
                      Most recent server version notified for hook: 6410
                      Last synced with client version: 6406
                      Last received by client: 6406
com.appjangle.database.hooks.HookConnection@229cf626: Notify updates.
                      Hook id: cknr6vdguucr3fq
                      Most recent server version notified for hook: 6410
                      Last synced with client version: 6406
                      Last received by client: 6406
com.appjangle.database.hooks.HookConnection$3$3@7334237c: All Hook messages processed [com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@4d375207, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@56c59e82, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@444dc9a2, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@38e3a25b]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@39d6dd07, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@72df11c4, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@32729329]
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@39d6dd07
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@72df11c4
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@32729329
com.appjangle.database.hooks.HookConnection@229cf626: Notify updates.
                      Hook id: djauvenk7pkrmny
                      Most recent server version notified for hook: 6409
                      Last synced with client version: 6404
                      Last received by client: 6404
com.appjangle.database.hooks.HookConnection@229cf626: Notify updates.
                      Hook id: bcvhovp3hfr5qx2
                      Most recent server version notified for hook: 6410
                      Last synced with client version: 6408
                      Last received by client: 6408
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@22a2928b, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@70b19e5d, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@2a35f83, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@7d066ded, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@4b868e0c, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@37b9b257, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@2ffeac64, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@6159c573, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@1ed0c1ba, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@6401f33d, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@3e46ee55, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@111bd6b3, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@9de083b, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@622d9a26, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@6b90f470, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@247119ff, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@5d97529a, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@53e50fa4]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@4fb3782a, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@35f8ced0, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@1fd21114, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@3a8699cf, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@6e20d49d]
com.appjangle.database.hooks.HookConnection@229cf626: Received change com.appjangle.messages.hook.changes.v01.ValueChangedChangeData@5464034b
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@5f06f1a1, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@5b743798, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@5abd5e6b, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@303b511f, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@58582540, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@22ea0124, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@12945d14]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@3719d24b, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@c2053ff, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@12653651, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@5a7ba504]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@114079c2]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@47978bd7]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@3f3a52dc, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@13280a25, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@74cc9958, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@faf204a, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@62ee2fd1, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@3144788b, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@215231a2, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@5709f8b2, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@448ac525, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@56986d1f, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@6677894f, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@7ea3315b, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@6c126047, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@79f7184f, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@2390cbcf, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@445e1f0f, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@3b315f9b, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@7a450dd2, com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@5fae7fe6]
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@22a2928b
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@70b19e5d
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@2a35f83
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@7d066ded
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@4b868e0c
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@37b9b257
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@2ffeac64
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@6159c573
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@1ed0c1ba
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@6401f33d
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@3e46ee55
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@111bd6b3
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@9de083b
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@622d9a26
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@6b90f470
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@247119ff
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@5d97529a
com.appjangle.database.hooks.HookConnection@229cf626: Processing hook message com.appjangle.messages.hook.v01.CheckForUpdatesMessageData@53e50fa4
com.appjangle.database.hooks.HookConnection@229cf626: Notify updates.
                      Hook id: 87ya25rw1nd87zt
                      Most recent server version notified for hook: 6409
                      Last synced with client version: 6405
                      Last received by client: 6405
com.appjangle.database.hooks.HookConnection@229cf626: Received change com.appjangle.messages.hook.changes.v01.DatabaseAddedChangeData@1ae0bcd7
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.RequestHookMessageData@65cb7e9b]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.RequestHookMessageData@7ce5f015]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.RequestHookMessageData@1288e1c9]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.RequestHookMessageData@36ad638a]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.RequestHookMessageData@612821d7]
com.appjangle.database.hooks.HookConnection@229cf626: Received hook messages [com.appjangle.messages.hook.v01.RequestHookMessageData@593f232a]

```

**Comment by mxro** [comment]
Reworked SequentialOperationsScheduler in [delight-concurrency](https://github.com/javadelight/delight-concurrency).

**Comment by objecthub-io** [comment]
Does not appear anymore in ObjectHub
