### ISSUE TITLE
Synchronization with Git Repo does not work

### ISSUE THREAD

**Issue by objecthub-io** [stellardb/StellarDB#87]
Error reported:

```
Exception in thread "delight.scheduler.BetterAccessThreadImplementation@3c56ab27" java.lang.IllegalArgumentException: Folder [/data/databases/git/objecthub-js/objecthub-js/src/main/web/prod/platform/ObjectHub Web/Screens/Explorer] cannot be deleted since it doesn't exist.
	at de.mxro.file.internal.jre.Java5FileItem.deleteFolder(Java5FileItem.java:120)
	at io.objecthub.filesync.internal.engine.convert.FolderToNode$3.apply(FolderToNode.java:156)
	at io.objecthub.filesync.internal.engine.convert.FolderToNode$3.apply(FolderToNode.java:1)
	at io.objecthub.filesync.internal.engine.FileUtils.execute(FileUtils.java:60)
	at io.objecthub.filesync.internal.engine.SyncFolder$2.apply(SyncFolder.java:81)
	at io.objecthub.filesync.internal.engine.SyncFolder$2.apply(SyncFolder.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at io.objecthub.filesync.internal.engine.NetworkToFileOperations$3$2$1.apply(NetworkToFileOperations.java:148)
	at io.objecthub.filesync.internal.engine.NetworkToFileOperations$3$2$1.apply(NetworkToFileOperations.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at delight.async.flow.CallbackAggregator$1.onSuccess(CallbackAggregator.java:72)
	at io.objecthub.filesync.internal.engine.NetworkToFileOperations$4.apply(NetworkToFileOperations.java:167)
	at io.objecthub.filesync.internal.engine.NetworkToFileOperations$4.apply(NetworkToFileOperations.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at delight.async.flow.CallbackAggregator$1.onSuccess(CallbackAggregator.java:72)
	at io.objecthub.filesync.internal.engine.convert.FileToTextNode$7.apply(FileToTextNode.java:276)
	at io.objecthub.filesync.internal.engine.convert.FileToTextNode$7.apply(FileToTextNode.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at io.objecthub.filesync.internal.engine.convert.FileToTextNode.obtainValueNode(FileToTextNode.java:214)
	at io.objecthub.filesync.internal.engine.convert.FileToTextNode.updateFiles(FileToTextNode.java:279)
	at io.objecthub.filesync.internal.engine.convert.ConverterCollection$11.apply(ConverterCollection.java:195)
	at io.objecthub.filesync.internal.engine.convert.ConverterCollection$11.apply(ConverterCollection.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at io.objecthub.filesync.internal.engine.convert.ConverterCollection.findConverter(ConverterCollection.java:94)
	at io.objecthub.filesync.internal.engine.convert.ConverterCollection.updateFiles(ConverterCollection.java:198)
	at io.objecthub.filesync.internal.engine.NetworkToFileOperations.deduceUpdateOperations(NetworkToFileOperations.java:172)
	at io.objecthub.filesync.internal.engine.NetworkToFileOperations$3$2.apply(NetworkToFileOperations.java:154)
	at io.objecthub.filesync.internal.engine.NetworkToFileOperations$3$2.apply(NetworkToFileOperations.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at delight.async.flow.CallbackAggregator$1.onSuccess(CallbackAggregator.java:72)
	at io.objecthub.filesync.internal.engine.NetworkToFileOperations$3$1$1$4.apply(NetworkToFileOperations.java:118)
	at io.objecthub.filesync.internal.engine.NetworkToFileOperations$3$1$1$4.apply(NetworkToFileOperations.java:1)
	at delight.promise.internal.PromiseImpl$3.onSuccess(PromiseImpl.java:225)
	at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:142)
	at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
	at com.ononedb.nextweb.OnedbLink$1$1.thenDo(OnedbLink.java:114)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1$1.run(LoadAndSynchronizeOperation.java:87)
	at one.engine.nx.internal.CallbackSequencer$1.run(CallbackSequencer.java:43)
	at one.engine.nx.internal.ClientWrapper$5.process(ClientWrapper.java:203)
	at delight.scheduler.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:131)
	at delight.scheduler.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:118)
	at delight.scheduler.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:81)
	at delight.concurrency.jre.JavaExecutor$4.run(JavaExecutor.java:83)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Stopping after processing nodes:

```
Processing https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Service1/.n/Deploy/.n/Deploy_to_Amazon_Display/app_tests/envs/env1467069438588/params/param1467069459291/object
Processing https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Service1/.n/Deploy/.n/Deploy_to_Amazon_Display/app_tests/envs/env1467069438588/params/param1467069459291/value
Processing https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Service1/.n/Deploy/.n/Deploy_to_Amazon_Display/app_tests/envs/env1467069438588/params/param1467069459291/type
Processing https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Service1/.n/Deploy/.n/Deploy_to_Amazon_Display/app_tests/envs/env1467069438588/params/param1467069480247/object
Processing https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Service1/.n/Deploy/.n/Deploy_to_Amazon_Display/app_tests/envs/env1467069438588/params/param1467069480247/value
Processing https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Service1/.n/Deploy/.n/Deploy_to_Amazon_Display/app_tests/envs/env1467069438588/params/param1467069480247/type
Processing https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Service1/.n/Deploy/.n/Deploy_to_Amazon_Display/app_tests/envs/env1467069438588/compilation/app_css
Processing https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Service1/.n/Deploy/.n/Deploy_to_Amazon_Display/app_tests/envs/env1467069438588/compilation/app_js
Processing https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Service1/.n/Deploy/.n/Deploy_to_Amazon_Display/app_tests/envs/env1467069438588/compilation/app_version
Processing https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Service1/.n/Deploy/.n/Deploy_to_Amazon_Display/app_tests/envs/env1467069438588/compilation/app_html
```

**Comment by objecthub-io** [comment]
Fixed.
