### ISSUE TITLE
StackOverflowError during clearVersions

### ISSUE THREAD

**Issue by stellardb** [stellardb/StellarDB#93]
HookConnection's VersionDb issues the following exception during clearing of versions:

```
Exception in thread "com.appjangle.database.hooks.HookConnection@7bf9b098->schedule" java.lang.RuntimeException: java.lang.StackOverflowError
	at com.appjangle.database.hooks.internal.VersionDb$7$1$1$1$1.onFailure(VersionDb.java:302)
	at delight.scheduler.SequentialOperationScheduler$1.onFailure(SequentialOperationScheduler.java:97)
	at delight.scheduler.SequentialOperationScheduler$4.run(SequentialOperationScheduler.java:299)
	at delight.concurrency.jre.JavaExecutor$4.run(JavaExecutor.java:83)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StackOverflowError
	at delight.keyvalue.internal.decorators.CollectMetricsStore.performOperation(CollectMetricsStore.java:148)
	at delight.keyvalue.internal.decorators.KeyFilterStore.performOperation(KeyFilterStore.java:72)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.performOperation(PrefixFilterStore.java:70)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.performOperation(ExceptionOnStartAndStopStore.java:67)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation.delete(DeleteOperation.java:67)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation.access$0(DeleteOperation.java:44)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation$1$1.run(DeleteOperation.java:37)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation$5.apply(DeleteOperation.java:176)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at delight.keyvalue.internal.decorators.CollectMetricsStore$2.onSuccess(CollectMetricsStore.java:63)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:68)
	at delight.keyvalue.internal.decorators.CollectMetricsStore.get(CollectMetricsStore.java:49)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation.determineLastIndex(DeleteOperation.java:166)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation.access$1(DeleteOperation.java:165)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation$1.run(DeleteOperation.java:33)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation$4.apply(DeleteOperation.java:159)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at delight.keyvalue.internal.decorators.CollectMetricsStore$2.onSuccess(CollectMetricsStore.java:63)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:68)
	at delight.keyvalue.internal.decorators.CollectMetricsStore.get(CollectMetricsStore.java:49)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation.determineFirstIndex(DeleteOperation.java:149)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation.perform(DeleteOperation.java:29)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$5.apply(InternalKeyValueDatabaseImpl.java:195)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$5.apply(InternalKeyValueDatabaseImpl.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$8.apply(InternalKeyValueDatabaseImpl.java:276)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at delight.keyvalue.internal.decorators.CollectMetricsStore$2.onSuccess(CollectMetricsStore.java:63)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:68)
	at delight.keyvalue.internal.decorators.CollectMetricsStore.get(CollectMetricsStore.java:49)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.find(InternalKeyValueDatabaseImpl.java:265)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.delete(InternalKeyValueDatabaseImpl.java:186)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$6.apply(InternalKeyValueDatabaseImpl.java:220)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$6.apply(InternalKeyValueDatabaseImpl.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$14$1$1.apply(InternalKeyValueDatabaseImpl.java:448)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$14$1$1.apply(InternalKeyValueDatabaseImpl.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$9.apply(InternalKeyValueDatabaseImpl.java:295)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at delight.keyvalue.internal.decorators.CollectMetricsStore$2.onSuccess(CollectMetricsStore.java:63)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:68)
	at delight.keyvalue.internal.decorators.CollectMetricsStore.get(CollectMetricsStore.java:49)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.find(InternalKeyValueDatabaseImpl.java:284)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$14$1.apply(InternalKeyValueDatabaseImpl.java:428)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at delight.keyvalue.internal.decorators.CollectMetricsStore$2.onSuccess(CollectMetricsStore.java:63)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:68)
	at delight.keyvalue.internal.decorators.CollectMetricsStore.get(CollectMetricsStore.java:49)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$14.apply(InternalKeyValueDatabaseImpl.java:412)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at delight.keyvalue.internal.decorators.CollectMetricsStore$2.onSuccess(CollectMetricsStore.java:63)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:68)
	at delight.keyvalue.internal.decorators.CollectMetricsStore.get(CollectMetricsStore.java:49)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:1)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.first(InternalKeyValueDatabaseImpl.java:401)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl.deleteFirst(InternalKeyValueDatabaseImpl.java:211)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$6$1.apply(InternalKeyValueDatabaseImpl.java:225)
	at com.appjangle.persistence.database.internal.InternalKeyValueDatabaseImpl$6$1.apply(InternalKeyValueDatabaseImpl.java:1)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation$2.onSuccess(DeleteOperation.java:59)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation$2.onSuccess(DeleteOperation.java:1)
	at delight.async.flow.CallbackAggregator$1.onSuccess(CallbackAggregator.java:72)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation.delete(DeleteOperation.java:135)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation.access$0(DeleteOperation.java:44)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation$1$1.run(DeleteOperation.java:37)
	at com.appjangle.persistence.database.internal.operations.DeleteOperation$5.apply(DeleteOperation.java:176)
	at delight.async.AsyncCommon$11.onSuccess(AsyncCommon.java:370)
	at delight.keyvalue.internal.decorators.CollectMetricsStore$2.onSuccess(CollectMetricsStore.java:63)
	at delight.keyvalue.internal.decorators.SimpleCachedStore.get(SimpleCachedStore.java:68)
	at delight.keyvalue.internal.decorators.CollectMetricsStore.get(CollectMetricsStore.java:49)
	at delight.keyvalue.internal.decorators.KeyFilterStore.get(KeyFilterStore.java:30)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:32)
	at delight.keyvalue.internal.decorators.PrefixFilterStore.get(PrefixFilterStore.java:1)
	at delight.keyvalue.internal.decorators.ExceptionOnStartAndStopStore.get(ExceptionOnStartAndStopStore.java:31)
...
```

**Comment by stellardb** [comment]
Fixed.
